#Броня

{1}{}{PID_PURPLE_ROBE@Сшейте из старых кусков ткани один большой мешок, а потом добавьте к нему капюшон и рукава. Покрасить это дело соком из лепестков цветов - и вы уже похожи на хаболога!@@SK_OUTDOORSMAN 40@PID_RAGS 6&PID_POCKET_LINT 2&PID_BROC_FLOWER 2&PID_BOOZE 1@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_PURPLE_ROBE 1@exp 225 script fix_boy@fix_AnyStuff1 }
{2}{}{PID_LEATHER_JACKET@Сшейте куртку из шкурок, а затем замочите в красящем растворе.@@SK_OUTDOORSMAN 50&SK_REPAIR 35@PID_GECKO_PELT 4&PID_POCKET_LINT 1&PID_CHEMICALS 1@PID_SEWING_KIT 1&PID_COMBAT_KNIFE 1|PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_SHIV 1@PID_LEATHER_JACKET 1@exp 310 script fix_boy@fix_AnyStuff2 }
{3}{}{PID_LEATHER_ARMOR@Шкуры брамина, сшитые в несколько слоёв, позволят чувствовать себя защищённей. Используйте шкуры гекко для придания эластичности в местах сгибов.@@SK_OUTDOORSMAN 60&SK_REPAIR 40@PID_BRAHMIN_SKIN 2&PID_GECKO_PELT 5&PID_POCKET_LINT 1&PID_ROPE 1@PID_SEWING_KIT 1&PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_COMBAT_KNIFE 1@PID_LEATHER_ARMOR 1@exp 400 script fix_boy@fix_AnyStuff2 }
{4}{}{PID_LEATHER_ARMOR_MK_II@Укрепите броню прочными шкурами золотых гекконов и обработайте её химикатами для улучшения защитных свойств.@SK_OUTDOORSMAN 30@SK_OUTDOORSMAN 70&SK_REPAIR 50@PID_LEATHER_ARMOR 1&PID_CHEMICALS 1&PID_GOLDEN_GECKO_PELT 3@PID_SEWING_KIT 1&PID_COMBAT_KNIFE 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_LEATHER_ARMOR_MK_II 1@exp 350 script fix_boy@fix_AnyStuff1 }
{5}{}{PID_CURED_LEATHER_ARMOR@Если на горизонте показались проблемы, то лучше забыть про стиль и укрепить свою старую добрую куртку ещё десятком слоёв кожи.@SK_OUTDOORSMAN 50@SK_OUTDOORSMAN 65&SK_REPAIR 60@PID_LEATHER_JACKET 1&PID_BRAHMIN_SKIN 2&PID_GOLDEN_GECKO_PELT 2&PID_POCKET_LINT 1@PID_SEWING_KIT 1&PID_SHIV 1|PID_COMBAT_KNIFE 1@PID_CURED_LEATHER_ARMOR 1@exp 350 script fix_boy@fix_AnyStuff1 }
{6}{}{PID_METAL_ARMOR@Боитесь ножей из-за угла и когтей гекко? С вашей новой металлической бронёй они будут для вас не больше, чем царапинами.@SK_REPAIR 70@SK_REPAIR 125@PID_METAL_TRASH 12&PID_PUMP_PARTS 3&PID_LEATHER_ARMOR 1&PID_WELDING 2@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1@PID_METAL_ARMOR 1@exp 550 script fix_boy@fix_AnyStuff3 }
{7}{}{PID_METAL_ARMOR_MK_II@Укрепите слабые места на броне, а затем обработайте напильником и отполируйте до блеска для лучше защиты от лазерного оружия.@SK_REPAIR 120@SK_REPAIR 150@PID_METAL_ARMOR 1&PID_METAL_TRASH 6&PID_WELDING 1@PID_MULTI_TOOL 1&PID_MOUSE_SKIN 1@PID_METAL_ARMOR_MK_II 1@exp 400 script fix_boy@fix_AnyStuff2 }
{8}{}{PID_TESLA_ARMOR@Понадобится рабочий станок, чтобы установить на свою металлическую броню катушки Тесла для рассеивания зарядов энергооружия. И не забудьте про шапочку из фольги!@SK_REPAIR 110&SK_SCIENCE 110@SK_REPAIR 150&SK_SCIENCE 140&SK_ENERGY_WEAPONS 140@PID_METAL_ARMOR_MK_II 1&PID_METAL_TRASH 10&PID_ELECTRONIC_WASTE 5&PID_PUMP_PARTS 6&PID_V15_COMPUTER_PART 5&PID_MICRO_FUSION_CELL 50@PID_WORKBENCH_INV 1&PID_SUPER_TOOL_KIT 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_BOOK_OF_ENERGY_WEAPON 1@PID_TESLA_ARMOR 1@exp 1400 script fix_boy@fix_TeslaArmor }
{9}{}{PID_COMBAT_ARMOR@Воспользуйтесь рабочим станком, чтобы сделать свою металлическую броню более легкой, соединив и обшив металлические пластины прочнейшими шкурами огненных гекконов. На эту основу нанесите прочные полимеры, выделив их при помощи химикатов из различного мусора.@SK_REPAIR 120&SK_SCIENCE 120@SK_REPAIR 160&SK_SCIENCE 140&SK_OUTDOORSMAN 125@PID_METAL_ARMOR_MK_II 1&PID_WELDING 2&PID_PUMP_PARTS 6&PID_FIRE_GECKO_PELT 12&PID_POLYMER 5@PID_WORKBENCH_INV 1&PID_SUPER_TOOL_KIT 1&PID_SCOUT_HANDBOOK 1&PID_SHIV 1&PID_COMBAT_KNIFE 1@PID_COMBAT_ARMOR 1@exp 1875 script fix_boy@fix_CombatArmor }
{10}{}{PID_COMBAT_ARMOR_MK_II@Улучшите защитные свойства бронекомплекта кропотливо усилив все слабые места дополнительными слоями полимеров, нанесенных на тонко выделанную кожу гекко. Качественную сборку удастся сделать только на специальном станке.@SK_REPAIR 145&SK_SCIENCE 140@SK_REPAIR 180&SK_SCIENCE 170&SK_OUTDOORSMAN 145@PID_COMBAT_ARMOR 1&PID_METAL_TRASH 4&PID_FIRE_GECKO_PELT 6&PID_CHEMICALS 2&PID_POLYMER 3@PID_WORKBENCH_INV 1&PID_SUPER_TOOL_KIT 1&PID_SCOUT_HANDBOOK 1@PID_COMBAT_ARMOR_MK_II 1@exp 1800 script fix_boy@fix_CombatArmorMK2 }
{11}{}{PID_POWERED_ARMOR@Вам придется применить все свои познания в области науки и ремонта и иметь недюжинную силу, чтобы точно следуя руководству по ремонту силовой брони, суметь произвести сборку механизированного бронекомплекта. Вам понадобятся самые продвинутые инструменты и оборудование.@SK_REPAIR 170&SK_SCIENCE 160@SK_SCIENCE 200&SK_REPAIR 200&ST_STRENGTH 8@PID_COMBAT_ARMOR_MK_II 1&PID_TESLA_ARMOR 1&PID_WELDING 10&PID_METAL_TRASH 60&PID_PUMP_PARTS 10&PID_STEEL 22&PID_V15_COMPUTER_PART 16&PID_ELECTRONIC_WASTE 10&PID_ROBOT_MOTIVATOR 6&PID_MOTIVATOR 1&PID_OIL_CAN_TRUE 1&PID_POLYMER 10&PID_TOUCH_SENSOR 2&PID_MICRO_FUSION_CELL 200@PID_PWRARMOR_PARTS 1&PID_SUPER_SLEDGE 1&PID_TECHNICAL_MANUAL 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_DEANS_ELECTRONICS 1&PID_SUPER_TOOL_KIT 1@PID_POWERED_ARMOR 1@exp 18000 script fix_boy@fix_PoweredArmor }
{12}{}{PID_HARDENED_POWER_ARMOR@Текущая сборка ну просто никуда не годится. Броню можно перекалить и местами приварить дополнительную защиту. Главное - сумейте её потом собрать обратно.@SK_REPAIR 170&SK_SCIENCE 180@SK_SCIENCE 210&SK_REPAIR 215&ST_STRENGTH 8@PID_POWERED_ARMOR 1&PID_BOTTLE_FULL 40&PID_FIREWOOD 10&PID_STEEL 10&PID_WELDING 12&PID_METAL_TRASH 30&PID_POLYMER 6&PID_MICRO_FUSION_CELL 150@PID_PWRARMOR_PARTS 1&PID_SUPER_SLEDGE 1&PID_TECHNICAL_MANUAL 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_DEANS_ELECTRONICS 1&PID_SUPER_TOOL_KIT 1@PID_HARDENED_POWER_ARMOR 1@exp 12000 script fix_boy@fix_HardenedPowerArmor }
{13}{}{PID_ADVANCED_POWER_ARMOR@Создайте более совершенный экзоскелет, чем в стандартной силовой броне, а вместо стальных пластины используйте композитные металлокерамические материалы, чтобы не только заметно облегчить боекомплект, но и существенно улучшить защиту от всех типов воздействий. Придется потрудиться, чтобы разыскать довоенное оборудование, способное произвести на свет высокотехнологичные серво-механизмы.@SK_REPAIR 190&SK_SCIENCE 190@SK_SCIENCE 230&SK_REPAIR 235@PID_WELDING 15&PID_METAL_TRASH 45&PID_METAL_CERAMICS 18&PID_V15_COMPUTER_PART 30&PID_ROBOT_PARTS 5&PID_ROBOT_MOTIVATOR 6&PID_K9_MOTIVATOR 2&PID_OIL_CAN_TRUE 2&PID_ELECTRONIC_WASTE 35&PID_TOUCH_SENSOR 2&PID_MICRO_FUSION_CELL 300@PID_PROD_PLANT2_INV 1&PID_TECHNICAL_MANUAL 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_DEANS_ELECTRONICS 1&PID_SUPER_TOOL_KIT 1@PID_ADVANCED_POWER_ARMOR 1@exp 30000 script fix_boy@fix_AdvancedPowerArmor }
{14}{}{PID_ADVANCED_POWER_ARMOR_MK2@Хорошенько подумав, вы понимаете, что даже улучшенный силовой боекомплект можно усовершенствовать, более эффективно смонтировав композитные пластины, а места стыков укрепив карбон полимерными материалами. Из чипа навигационного компьютера можно собрать и вмонтировать в шлем систему, улучшающую ваше ориентирование на местности.@SK_REPAIR 200&SK_SCIENCE 200@SK_SCIENCE 250&SK_REPAIR 240@PID_ADVANCED_POWER_ARMOR 1&PID_WELDING 8&PID_METAL_CERAMICS 7&PID_NAVCOM_PARTS 1&PID_V15_COMPUTER_PART 20&PID_ELECTRONIC_WASTE 15&PID_CARBON 12&PID_MICRO_FUSION_CELL 200@PID_PROD_PLANT2_INV 1&PID_TECHNICAL_MANUAL 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_DEANS_ELECTRONICS 1&PID_SUPER_TOOL_KIT 1@PID_ADVANCED_POWER_ARMOR_MK2 1@exp 20000 script fix_boy@fix_AdvancedPowerArmorMK2 }
{15}{}{PID_MANTIS_ARMOR@Разломайте панцири мантиссов на мелкие кусочки. Осторожно помешивая, опустите в кипящие химикаты. На медленном огне варите смесь до растворения хитина и получения однородной массы. Расплав слоями перенесити на ткань, укрепленную тонко выделанной кожей гекко, каждый слой ткани и расплава отформовать по фигуре.@SK_REPAIR 100&SK_OUTDOORSMAN 125@SK_REPAIR 150&SK_OUTDOORSMAN 175&SK_SCIENCE 125&ST_INTELLECT 6@PID_MANTIS_CHITIN 40&PID_CHEMICALS 4&PID_RAGS 12&PID_METAL_TRASH 9&PID_GOLDEN_GECKO_PELT 5&PID_BOTTLE_FULL 3@PID_FIREPIT_INV 1&PID_SUPER_TOOL_KIT 1&PID_SCOUT_HANDBOOK 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_SHIV 1&PID_COMBAT_KNIFE 1@PID_MANTIS_ARMOR 1@exp 1750 script fix_boy@fix_MantisArmor }




#Патроны

{100}{}{PID_SHOTGUN_SHELLS@Надо обладать недюжинной силой воли для того, чтобы пустить на пыжи такой журнал, как "Кошачья лапка".@SK_REPAIR 50&SK_SMALL_GUNS 80@SK_SCIENCE 50&SK_SMALL_GUNS 100&SK_REPAIR 80@PID_GUNPOWDER 3&PID_CATS_PAW 1&PID_REAL_BOTTLE_CAPS 40&PID_PUMP_PARTS 2@PID_MULTI_TOOL 1@PID_SHOTGUN_SHELLS 30@exp 100 script fix_boy@fix_AnyStuff2 }
{101}{}{PID_10MM_JHP@Зафиксируйте патроны на чём-нибудь устойчивом струбциной, стараясь не смять гильзу. Затем обрежьте кончики пуль, высверлите часть сердечника и загните края латунной оболочки внутрь, сделав в ней небольшие надрезы. Теперь пуля будет разрываться от удара о цель.@SK_REPAIR 30@SK_REPAIR 90&SK_SMALL_GUNS 90@PID_10MM_AP 20@PID_MULTI_TOOL 1@PID_10MM_JHP 20@exp 100 script fix_boy@fix_AnyStuff1 }
{102}{}{PID_5MM_JHP@Зафиксируйте патроны на чём-нибудь устройчивом струбциной, стараясь не смять гильзу. Затем обрежьте кончики пуль, высверлите часть сердечника и загните края латунной оболочки внутрь, сделав в ней небольшие надрезы. Теперь пуля будет разрываться от удара о цель.@SK_REPAIR 50@SK_REPAIR 90&SK_SMALL_GUNS 130|SK_BIG_GUNS 130@PID_5MM_AP 20@PID_MULTI_TOOL 1@PID_5MM_JHP 20@exp 100 script fix_boy@fix_AnyStuff1 }
{103}{}{PID_44_MAGNUM_JHP@Зафиксируйте патроны на чём-нибудь устройчивом струбциной, стараясь не смять гильзу. Затем обрежьте кончики пуль, высверлите небольшое углубление в сердцевине и загните края латунной оболочки внутрь, сделав в ней небольшие надрезы. Теперь пуля будет разрываться от удара о цель.@SK_REPAIR 50@SK_REPAIR 90&SK_SMALL_GUNS 130@PID_44_FMJ_MAGNUM 20@PID_MULTI_TOOL 1@PID_44_MAGNUM_JHP 20@exp 100 script fix_boy@fix_AnyStuff1 }
{104}{}{PID_BBS@Нагрейте кусочки свинца до температуры плавления зажигалкой и залейте в формочки.@@SK_REPAIR 30@PID_METAL_TRASH 1@PID_MULTI_TOOL 1&PID_LIGHTER 1@PID_BBS 20@exp 100 script fix_boy@fix_AnyStuff1 }
{105}{}{PID_HN_NEEDLER_CARTRIDGE@Вырежьте подходящие кусочки пластика, в которые можно облачить мини-шприцы, наполненные ядом.@SK_SCIENCE 100&SK_DOCTOR 80@SK_SCIENCE 140&SK_DOCTOR 120&SK_REPAIR 140@PID_PUMP_PARTS 2&PID_CHEMICALS 1@PID_MULTI_TOOL 1&PID_CHEMISTRY_MANUAL 1&PID_FIRST_AID_BOOK 1&PID_PARAMEDICS_BAG 1@PID_HN_NEEDLER_CARTRIDGE 20@exp 200 script fix_boy@fix_AnyStuff3 }
{106}{}{PID_HN_AP_NEEDLER_CARTRIDGE@Приделайте инъекторам остро заточенные металлические наконечники.@SK_REPAIR 90@SK_REPAIR 140@PID_HN_NEEDLER_CARTRIDGE 20&PID_METAL_TRASH 2@PID_MULTI_TOOL 1@PID_HN_AP_NEEDLER_CARTRIDGE 20@exp 150 script fix_boy@fix_AnyStuff1 }
{107}{}{PID_EXPLOSIVE_ROCKET@Получите нитроцеллюлозу путём воздействия на древесину смеси серной и азотной кислоты, она будет использоваться как топливо для реактивного двигателя, а нитроглицерин как окислитель. Соберите ракету в корпусе выточенном из отрезка трубы, взрывчатым веществом для боеголовки послужит тротил. Вы уже предвкушаете, как чьи-нибудь внутренности разлетятся по округе.@SK_REPAIR 80&SK_SCIENCE 80@SK_REPAIR 120&SK_SCIENCE 120@PID_TUBE 2&PID_METAL_TRASH 4&PID_FIREWOOD 2&PID_CHEMICALS 1&PID_NITROGLYCERIN 3&PID_TNT 3@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1&PID_BIG_BOOK_OF_SCIENCE 1@PID_EXPLOSIVE_ROCKET 6@exp 300 script fix_boy@fix_ExplosiveRocket}
{108}{}{PID_ROCKET_AP@Выточите на токарном станке пару наконечников из куска стали. Теперь ваша ракета будет более эффективна против бронированных целей. К сожалению, частью взрывчатого вещества пришлось пожертвовать.@SK_REPAIR 90@SK_REPAIR 140@PID_EXPLOSIVE_ROCKET 2&PID_METAL_TRASH 1&PID_STEEL 1@PID_MANUFACT_LATHE_INV 1&PID_MULTI_TOOL 1@PID_ROCKET_AP 2@exp 100 script fix_boy@fix_RocketAP}
{109}{}{PID_40MM_GRANADE@Поместите нитроглицерин в металлический корпус гранаты, холостой патрон калибра 7.62 мм придаст гранате необходимое ускорение.@SK_REPAIR 110&SK_SCIENCE 80@SK_REPAIR 140&SK_SCIENCE 100@PID_PUMP_PARTS 3&PID_METAL_TRASH 4&PID_NITROGLYCERIN 2&PID_7_62MM_AMMO 3@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1@PID_40MM_GRANADE 3@exp 175 script fix_boy@fix_ExplosiveRocket }
{110}{}{PID_CANNON_BALLS@Расплавьте сталь, вылейте расплав в шарообразную форму и отшлифуйте на токарном станке. Снаряд готов к путешествию вместе с вашим врагом.@SK_REPAIR 150@SK_REPAIR 200@PID_STEEL 2&PID_WELDING 1&PID_GUNPOWDER 3@PID_MANUFACT_LATHE_INV 1&PID_MULTI_TOOL 1&PID_BIG_BOOK_OF_SCIENCE 1@PID_CANNON_BALLS 1@exp 180 script fix_boy@fix_RocketAP }
{111}{}{PID_SMALL_ENERGY_CELL@Следуя руководству по созданию высокоэффективной батареи в «Науке для каждого», соберите герметичный корпус из железяк, залейте в него щелочь, а кадмий для электродов и графитовый порошок выделите из минералов.@SK_SCIENCE 150@SK_SCIENCE 175@PID_CHEMICALS 1&PID_MINERAL 2&PID_METAL_TRASH 2@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1&PID_BIG_BOOK_OF_SCIENCE 1@PID_SMALL_ENERGY_CELL 40@exp 150 script fix_boy@fix_MagnetoLaserPistol }
{112}{}{PID_MICRO_FUSION_CELL@Используйте в качестве источника энергии в радиоизотопной батарее обогащенную урановую руду, а корпус изготовьте из свинца, выделенного из железной руды. Сборку производите только в радиозащищенной установке.@SK_SCIENCE 160@SK_SCIENCE 210@PID_METAL_TRASH 2&PID_METAL_ORE 1&PID_REFINED_ORE 1@PID_MULTICRAFT_INV 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_CHEMISTRY_MANUAL 1@PID_MICRO_FUSION_CELL 30@exp 240 script fix_boy@fix_Carbon }
{113}{}{PID_NAILS@Накалите и растягивайте железные прутики, заостряя концы гвоздей и оставляя утолщения на местах шляпок.@SK_REPAIR 50@SK_REPAIR 80@PID_METAL_TRASH 2@PID_MULTI_TOOL 1&PID_LIGHTER 1@PID_NAILS 80@exp 80 script fix_boy@fix_AnyStuff3 }




#Патроны - рецепты для станков (это потом уберётся, будет крафт через диалог станка)

{120}{}{PID_9MM_BALL@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны 9 мм, цельнометаллические".@@SK_SMALL_GUNS 60&SK_REPAIR 75@PID_GUNPOWDER 1&PID_STEEL 1@PID_MANUFACT_AMMO1_INV 1@PID_9MM_BALL 20@exp 100 script fix_boy@fix_AnyRounds1}
{121}{}{PID_9MM_AMMO@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны 9 мм".@@SK_SMALL_GUNS 50&SK_REPAIR 50@PID_GUNPOWDER 1&PID_METAL_TRASH 2@PID_MANUFACT_AMMO1_INV 1@PID_9MM_AMMO 20@exp 75 script fix_boy@fix_AnyRounds1}
{122}{}{PID_10MM_JHP@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны 10 мм, полуоболоченные".@@SK_SMALL_GUNS 50&SK_REPAIR 50@PID_GUNPOWDER 1&PID_METAL_TRASH 2@PID_MANUFACT_AMMO1_INV 1@PID_10MM_JHP 20@exp 75 script fix_boy@fix_AnyRounds1}
{123}{}{PID_10MM_AP@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны 10 мм, бронебойные".@@SK_SMALL_GUNS 60&SK_REPAIR 60@PID_GUNPOWDER 1&PID_METAL_TRASH 1&PID_STEEL 1@PID_MANUFACT_AMMO1_INV 1@PID_10MM_AP 20@exp 100 script fix_boy@fix_AnyRounds1}
{124}{}{PID_44_MAGNUM_JHP@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны калибра .44".@@SK_SMALL_GUNS 120&SK_SCIENCE 45&SK_REPAIR 60@PID_GUNPOWDER 1&PID_METAL_TRASH 2@PID_MANUFACT_AMMO1_INV 1@PID_44_MAGNUM_JHP 15@exp 75 script fix_boy@fix_AnyRounds1}
{125}{}{PID_44_FMJ_MAGNUM@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны калибра .44, цельнометаллические".@@SK_SMALL_GUNS 120&SK_SCIENCE 45&SK_REPAIR 70@PID_GUNPOWDER 1&PID_METAL_TRASH 1&PID_STEEL 1@PID_MANUFACT_AMMO1_INV 1@PID_44_FMJ_MAGNUM 20@exp 100 script fix_boy@fix_AnyRounds1}
{126}{}{PID_14MM_AP@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны 14мм, бронебойные".@@SK_SCIENCE 70&SK_REPAIR 80&SK_SMALL_GUNS 130|SK_BIG_GUNS 130@PID_GUNPOWDER 1&PID_METAL_TRASH 2&PID_STEEL 1@PID_MANUFACT_AMMO1_INV 1@PID_14MM_AP 20@exp 100 script fix_boy@fix_AnyRounds1}
{127}{}{PID_223_FMJ@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны .223, цельнометаллические".@@SK_SCIENCE 100&SK_REPAIR 125&SK_SMALL_GUNS 150|SK_BIG_GUNS 150@PID_GUNPOWDER 2&PID_METAL_TRASH 3&PID_STEEL 1@PID_MANUFACT_AMMO2_INV 1@PID_223_FMJ 30@exp 120 script fix_boy@fix_AnyRounds2}
{128}{}{PID_5MM_JHP@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны 5 мм, полуоболоченные".@@SK_SCIENCE 70&SK_REPAIR 90&SK_SMALL_GUNS 140|SK_BIG_GUNS 140@PID_GUNPOWDER 2&PID_METAL_TRASH 4@PID_MANUFACT_AMMO2_INV 1@PID_5MM_JHP 80@exp 120 script fix_boy@fix_AnyRounds2}
{129}{}{PID_5MM_AP@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны 5 мм, бронебойные".@@SK_SCIENCE 70&SK_REPAIR 90&SK_SMALL_GUNS 140|SK_BIG_GUNS 140@PID_GUNPOWDER 2&PID_METAL_TRASH 3&PID_STEEL 1@PID_MANUFACT_AMMO2_INV 1@PID_5MM_AP 80@exp 120 script fix_boy@fix_AnyRounds2}
{130}{}{PID_45_CALIBER_AMMO@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны калибра 0.45".@@SK_SMALL_GUNS 120&SK_SCIENCE 60&SK_REPAIR 80@PID_GUNPOWDER 1&PID_METAL_TRASH 2@PID_MANUFACT_AMMO1_INV 1@PID_45_CALIBER_AMMO 25@exp 100 script fix_boy@fix_AnyRounds1}
{131}{}{PID_7_62MM_AMMO@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны калибра 7,62, цельнометаллические".@@SK_SCIENCE 80&SK_REPAIR 120&SK_SMALL_GUNS 140|SK_BIG_GUNS 140@PID_GUNPOWDER 3&PID_STEEL 1&PID_METAL_TRASH 4@PID_MANUFACT_AMMO2_INV 1@PID_7_62MM_AMMO 50@exp 120 script fix_boy@fix_AnyRounds2}
{132}{}{PID_4_7MM_CASELESS@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны калибра 4.7 мм, безгильзовые". Для создания капсуля из нитроцеллюлозы вам понадобится азотная кислота и древесина.@@SK_SCIENCE 140&SK_REPAIR 175&SK_SMALL_GUNS 175|SK_BIG_GUNS 175@PID_GUNPOWDER 3&PID_METAL_TRASH 5&PID_STEEL 1&PID_FIREWOOD 3&PID_CHEMICALS 2@PID_MANUFACT_AMMO3_INV 1@PID_4_7MM_CASELESS 100@exp 210 script fix_boy@fix_AnyRounds3}
{133}{}{PID_2MM_EC_AMMO@Подключите свой Фикс-Бой к автоматическому станку и выберите программу "Патроны калибра 2мм, электромагнитные". Понадобится дополнительный источник питания для обоймы и станка.@SK_SCIENCE 120&SK_REPAIR 120@SK_SCIENCE 200&SK_REPAIR 175&SK_SMALL_GUNS 200@PID_METAL_CERAMICS 1&PID_ELECTRONIC_WASTE 1&PID_METAL_TRASH 6&PID_MICRO_FUSION_CELL 20@PID_MANUFACT_AMMO3_INV 1@PID_2MM_EC_AMMO 12@exp 300 script fix_boy@fix_AnyRounds3}
{134}{}{PID_700_NITRO_EXPRESS@Понадобятся некоторые познания в электронике и баллистике для того, чтобы запрограммировать станок на производство этих необычных патронов.@@SK_SMALL_GUNS 180&SK_SCIENCE 120&SK_REPAIR 150@PID_GUNPOWDER 1&PID_METAL_TRASH 1&PID_STEEL 1@PID_MANUFACT_LATHE_INV 1@PID_700_NITRO_EXPRESS 1@exp 100 script fix_boy@fix_NitroExpressRounds}


#Топлива

{200}{}{PID_MOLOTOV_COCKTAIL@Пойло, смешанное со смолянистым соком цветков, будет замечательно гореть и прилипать к противнику.@SK_SCIENCE 20@SK_SCIENCE 30&SK_OUTDOORSMAN 40@PID_ROT_GUT 1&PID_RAGS 1&PID_BROC_FLOWER 1@@PID_MOLOTOV_COCKTAIL 1@exp 100 script fix_boy@fix_AnyStuff1 }
{201}{}{PID_MOLOTOV_COCKTAIL@Нет огнемёта? Не беда, всегда можно найти способ доставить пламя до противника.@SK_SCIENCE 20@SK_SCIENCE 30&SK_REPAIR 30@PID_BOTTLE_GLASS 1&PID_RAGS 1&PID_FLAMETHROWER_FUEL 1@@PID_MOLOTOV_COCKTAIL 1@exp 100 script fix_boy@fix_AnyStuff1 }
{202}{}{PID_FLAMETHROWER_FUEL@Найдите в мусоре побольше пенопласта, растворяйте в ацетоне, пока эта смесь не станет густой. Дозаправьте баллон с топливом.@SK_SCIENCE 30@SK_SCIENCE 50&SK_REPAIR 60@PID_FLAMETHROWER_FUEL 1&PID_CHEMICALS 1&PID_POCKET_LINT 1&PID_PUMP_PARTS 2@@PID_FLAMETHROWER_FUEL 10@exp 150 script fix_boy@fix_AnyStuff2 }
{203}{}{PID_FLAMETHROWER_FUEL@Найдите в мусоре побольше пенопласта, растворяйте в ацетоне, пока эта смесь не станет густой. Заместите этой смесью газ в одном из баллонов сварки.@SK_SCIENCE 30@SK_SCIENCE 50&SK_REPAIR 60@PID_CHEMICALS 1&PID_POCKET_LINT 1&PID_PUMP_PARTS 2&PID_WELDING 1|PID_WELDING_USED 1@PID_MULTI_TOOL 1@PID_FLAMETHROWER_FUEL 10@exp 200 script fix_boy@fix_AnyStuff2 }
{204}{}{PID_FLAMETHROWER_FUEL@Смешайте пару видов крепчайшого самогона с растворенными в ацетоне фруктах для придания вязкости. Дозаправьте баллон с топливом.@SK_SCIENCE 30@SK_SCIENCE 50&SK_OUTDOORSMAN 60@PID_FLAMETHROWER_FUEL 1&PID_ROT_GUT 1&PID_BOOZE 1&PID_CHEMICALS 1&PID_MUTATED_FRUIT 1@@PID_FLAMETHROWER_FUEL 10@exp 100 script fix_boy@fix_AnyStuff2 }
{205}{}{PID_FLAMETHROWER_FUEL@Смешайте пару видов крепчайшого самогона с растворенными в ацетоне фруктах для придания вязкости. Заправьте полученную смесь в сварочный баллон и получите отличное топливо для огнемета.@SK_SCIENCE 30@SK_SCIENCE 50&SK_OUTDOORSMAN 60@PID_ROT_GUT 1&PID_BOOZE 1&PID_CHEMICALS 1&PID_MUTATED_FRUIT 1&PID_WELDING 1|PID_WELDING_USED 1@PID_MULTI_TOOL 1@PID_FLAMETHROWER_FUEL 10@exp 200 script fix_boy@fix_AnyStuff2 }
{206}{}{PID_FLAMETHROWER_FUEL_MKII@Добавьте ядерной колы для повышения скорости горения топлива. Не рекомендуется использовать его со стандартными моделями огнемётов во избежание забивания сопла.@SK_REPAIR 50&SK_OUTDOORSMAN 50@SK_SCIENCE 110&SK_OUTDOORSMAN 80@PID_FLAMETHROWER_FUEL 10&PID_NUKA_COLA 2@PID_MULTI_TOOL 1@PID_FLAMETHROWER_FUEL_MK_II 10@exp 100 script fix_boy@fix_AnyStuff1 }
{207}{}{PID_FLAMETHROWER_FUEL_MKII@Немного алюминиевой пудры, натёртой собственными руками, повысит температуру горения топлива. Не рекомендуется использовать его со стандартными моделями огнемётов во избежание забивания сопла.@SK_REPAIR 50&SK_SCIENCE 50@SK_SCIENCE 100&SK_REPAIR 90@PID_FLAMETHROWER_FUEL 10&PID_METAL_TRASH 2@PID_MULTI_TOOL 1@PID_FLAMETHROWER_FUEL_MK_II 10@exp 120 script fix_boy@fix_AnyStuff1 }

#Лёгкое

{300}{}{PID_SCOPED_HUNTING_RIFLE@Для простенького прицела сойдут и линзы из чьих-нибудь очков, главное - чётко следовать инструкциям.@SK_SMALL_GUNS 100&SK_REPAIR 75@SK_REPAIR 100&SK_SMALL_GUNS 120&SK_SCIENCE 80@PID_HUNTING_RIFLE 1&PID_SPECTACLES 1&PID_PUMP_PARTS 1&PID_METAL_TRASH 2@PID_GUNS_AND_BULLETS 1&PID_MULTI_TOOL 1@PID_SCOPED_HUNTING_RIFLE 1@exp 260 script fix_boy@fix_AnyStuff1 }
{301}{}{PID_ASSAULT_RIFLE_EXT_MAG@Изготовьте новый магазин и найдите в мусоре для него пружину помощнее.@SK_SMALL_GUNS 100&SK_REPAIR 80@SK_REPAIR 120&SK_SMALL_GUNS 120&SK_SCIENCE 80@PID_ASSAULT_RIFLE 1&PID_PUMP_PARTS 1&PID_METAL_TRASH 2@PID_GUNS_AND_BULLETS 1&PID_MULTI_TOOL 1@PID_ASSAULT_RIFLE_EXT_MAG 1@exp 160 script fix_boy@fix_AnyStuff1 }
{302}{}{PID_SHOTGUN@Найдите две трубы более-менее подходящего диаметра, изготовьте к ним приклад и простенький спусковой механизм.@SK_SMALL_GUNS 50@SK_SMALL_GUNS 80&SK_REPAIR 65@PID_SHOTGUN_SHELLS 2&PID_TUBE 2&PID_FIREWOOD 1&PID_PUMP_PARTS 2&PID_METAL_TRASH 2@PID_MULTI_TOOL 1@PID_SHOTGUN 1@exp 150 script fix_boy@fix_AnyStuff2 }
{303}{}{PID_SAWED_OFF_SHOTGUN@Укорачивание ствола на десяток дюймов позволит комфортно прятать дробовик под одеждой, чтобы удивлять противника в самый неподходящий момент.@SK_REPAIR 40@SK_REPAIR 60@PID_SHOTGUN 1@PID_MULTI_TOOL 1@PID_SAWED_OFF_SHOTGUN 1@exp 120 script fix_boy@fix_AnyStuff1 }
{304}{}{PID_COMBAT_SHOTGUN@Полностью переработав на станке механизм дробовика и добавив возможность стрельбы очередью, вы получите оружие, с которым не стыдно выступить в бою.@SK_SMALL_GUNS 100&SK_REPAIR 120@SK_SMALL_GUNS 140&SK_REPAIR 140&SK_SCIENCE 80@PID_SHOTGUN 1&PID_SHOTGUN_SHELLS 10&PID_PUMP_PARTS 4&PID_METAL_TRASH 6&PID_LUBRICANT 1@PID_WORKBENCH_INV 1&PID_GUNS_AND_BULLETS 1&PID_MULTI_TOOL 1@PID_COMBAT_SHOTGUN 1@exp 300 script fix_boy@fix_CombatShotgun }
{305}{}{PID_HK_CAWS@Придется хорошенько потрудиться на токарном станке, чтобы получить подобное автоматическое гладкоствольное ружье по схеме булл-пап.@SK_SMALL_GUNS 130&SK_REPAIR 125@SK_SMALL_GUNS 160&SK_REPAIR 140&SK_SCIENCE 100@PID_COMBAT_SHOTGUN 1&PID_SHOTGUN_SHELLS 10&PID_PUMP_PARTS 4&PID_METAL_TRASH 6&PID_POLYMER 2@PID_MANUFACT_LATHE_INV 1&PID_GUNS_AND_BULLETS 1&PID_MULTI_TOOL 1@PID_HK_CAWS 1@exp 580 script fix_boy@fix_HKCaws }
{306}{}{PID_PANCOR_JACKHAMMER@Изготовление совершенного орудия убийства, способного в секунды превратить группу людей в кровавый фарш, потребует от вас чуть больше сноровки, чем совокупление с брамином. Ключевые детали должны быть из самых прочных материалов.@SK_SMALL_GUNS 140&SK_REPAIR 150@SK_SMALL_GUNS 180&SK_REPAIR 175&SK_SCIENCE 120@PID_HK_CAWS 1&PID_SHOTGUN_SHELLS 10&PID_PUMP_PARTS 4&PID_METAL_TRASH 10&PID_POLYMER 3&PID_METAL_CERAMICS 1@PID_PROD_PLANT1_INV 1&PID_GUNS_AND_BULLETS 1&PID_SUPER_TOOL_KIT 1&PID_OIL_CAN_TRUE 1@PID_PANCOR_JACKHAMMER 1@exp 1050 script fix_boy@fix_PancorJackhammer }
{307}{}{PID_DESERT_EAGLE_EXT_MAG@С переделкой магазина придётся помучиться, но она сэкономит несколько драгоценных секунд в бою.@SK_SMALL_GUNS 70&SK_REPAIR 60@SK_REPAIR 80&SK_SMALL_GUNS 120&SK_SCIENCE 60@PID_DESERT_EAGLE 1&PID_PUMP_PARTS 1&PID_METAL_TRASH 2@PID_GUNS_AND_BULLETS 1&PID_MULTI_TOOL 1@PID_DESERT_EAGLE_EXT_MAG 1@exp 120 script fix_boy@fix_AnyStuff1 }
{308}{}{PID_SPRINGER_RIFLE@Замените ствол и выточьте нормальный приклад на своём самопале для увеличения точности.@@SK_REPAIR 40@PID_ZIP_GUN 1&PID_PUMP_PARTS 1&PID_FIREWOOD 1&PID_10MM_JHP 1@@PID_SPRINGER_RIFLE 1@exp 90 script fix_boy@fix_AnyStuff1 }
{309}{}{PID_ZIP_GUN@Прочно примотайте трубу проволокой к рукояти. Отнеситесь к этому серьёзно, иначе ваше оружие самоуничтожится после первого же выстрела.@@SK_REPAIR 30@PID_PUMP_PARTS 1&PID_METAL_TRASH 1&PID_10MM_JHP 1@@PID_ZIP_GUN 1@exp 90 script fix_boy@fix_AnyStuff1 }
{310}{}{PID_FN_FAL_HPFA@Пускай отдача будет ломать вам плечо, но это улучшение того стоит.@SK_SMALL_GUNS 120&SK_REPAIR 120@SK_SMALL_GUNS 150&SK_REPAIR 160&SK_SCIENCE 70@PID_FN_FAL 1&PID_METAL_TRASH 3&PID_PUMP_PARTS 2&PID_STEEL 2@PID_MULTI_TOOL 1&PID_GUNS_AND_BULLETS 1@PID_FN_FAL_HPFA 1@exp 220 script fix_boy@fix_AnyStuff2 }
{311}{}{PID_MAUSER_SMG@В одном из номеров журнала "Пушки и пули" была опубликована схема автоматического Маузера М712 калибра 7,62. Изучив её, вы поняли, что 9мм Маузер можно было бы переделать подобным образом.@SK_SMALL_GUNS 80@SK_REPAIR 80&SK_SMALL_GUNS 100@PID_9MM_MAUSER 1&PID_METAL_TRASH 1&PID_PUMP_PARTS 1@PID_MULTI_TOOL 1&PID_GUNS_AND_BULLETS 1@PID_MAUSER_SMG 1@exp 175 script fix_boy@fix_AnyStuff2 }
{312}{}{PID_10MM_PISTOL@Смастерите вашему самопалу приличный корпус и механизм подачи патронов и получите простейший пистолет.@SK_SMALL_GUNS 50@SK_REPAIR 50&SK_SMALL_GUNS 70@PID_ZIP_GUN 1&PID_METAL_TRASH 2&PID_PUMP_PARTS 2@PID_MULTI_TOOL 1@PID_10MM_PISTOL 1@exp 150 script fix_boy@fix_AnyStuff1 }
{313}{}{PID_10MM_SMG@Оснастите свой пистолет системой автоматического огня, основанной на использовании энергии пороховых газов, воздействующих через дно гильзы на затвор, не имеющего связи со стволом. Увеличьте обойму и получите смертоносное на ближних дистанциях оружие.@SK_SMALL_GUNS 70@SK_REPAIR 75&SK_SMALL_GUNS 100@PID_10MM_PISTOL 1&PID_METAL_TRASH 3&PID_PUMP_PARTS 2&PID_10MM_JHP 12|PID_10MM_AP 12@PID_MULTI_TOOL 1@PID_10MM_SMG 1@exp 200 script fix_boy@fix_AnyStuff2 }
{314}{}{PID_HUNTING_RIFLE@Ловко работая напильником, подгоните на станке тонкую трубу под калибр 5.56 мм, вырежьте приклад из дерева, а как создать механизм - вам подскажет статья из журнала «Пушки и пули». Не забудьте хорошенько пристрелять ваше творение!@SK_SMALL_GUNS 90&SK_REPAIR 70@SK_SMALL_GUNS 120&SK_REPAIR 110@PID_PUMP_PARTS 3&PID_FIREWOOD 2&PID_TUBE 1&PID_METAL_TRASH 5&PID_223_FMJ 5@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1&PID_GUNS_AND_BULLETS 1&PID_COMBAT_KNIFE 1@PID_HUNTING_RIFLE 1@exp 300 script fix_boy@fix_HuntingRifle }
{315}{}{PID_DESERT_EAGLE@Для такого пистолета вам придется соорудить систему отвода пороховых газов, а затворную раму выточить на токарном станке из подходящего куска стали.@SK_SMALL_GUNS 70&SK_REPAIR 90@SK_REPAIR 110&SK_SMALL_GUNS 120@PID_10MM_PISTOL 1&PID_METAL_TRASH 2&PID_PUMP_PARTS 1&PID_TUBE 1&PID_STEEL 1&PID_44_MAGNUM_JHP 12|PID_44_FMJ_MAGNUM 12@PID_MANUFACT_LATHE_INV 1&PID_MULTI_TOOL 1@PID_DESERT_EAGLE 1@exp 200 script fix_boy@fix_DesertEagle }
{316}{}{PID_14MM_PISTOL@От попадания из такой пушки голова брамина разлетается феерическим взрывом белоснежных осколков кости, сгустков мозга и фонтанчиков крови. Чего уж говорить о человеке. Главное, позаботьтесь о надежности этого монстра.@SK_SMALL_GUNS 80&SK_REPAIR 70@SK_REPAIR 100&SK_SMALL_GUNS 120@PID_10MM_PISTOL 1&PID_METAL_TRASH 2&PID_PUMP_PARTS 2&PID_TUBE 1&PID_STEEL 1&PID_14MM_AP 6@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1@PID_14MM_PISTOL 1@exp 220 script fix_boy@fix_14mmPistol }
{317}{}{PID_9MM_MAUSER@Слегка модифицируйте стандартный пистолет, придав ему облик немецкой легенды, и сможете выдавать себя за потомственного чекиста.@SK_SMALL_GUNS 60@SK_REPAIR 70&SK_SMALL_GUNS 90@PID_10MM_PISTOL 1&PID_METAL_TRASH 2&PID_PUMP_PARTS 1&PID_TUBE 1&PID_9MM_BALL 7|PID_9MM_AMMO 7@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1@PID_9MM_MAUSER 1@exp 140 script fix_boy@fix_9mmMauser }
{318}{}{PID_44_MAGNUM_REVOLVER@Придется хорошенько потрудиться за токарным станком, чтобы выточить основные части револьвера из качественной стали. Несколько часов труда ради того, чтобы почувствовать себя настоящим ковбоем, стоят того!@SK_SMALL_GUNS 120&SK_REPAIR 90@SK_REPAIR 120&SK_SMALL_GUNS 150@PID_METAL_TRASH 5&PID_PUMP_PARTS 3&PID_TUBE 1&PID_STEEL 2&PID_44_MAGNUM_JHP 6|PID_44_FMJ_MAGNUM 6@PID_MANUFACT_LATHE_INV 1&PID_MULTI_TOOL 1&PID_GUNS_AND_BULLETS 1@PID_44_MAGNUM_REVOLVER 1@exp 300 script fix_boy@fix_44MagnumRevolver }
{319}{}{PID_ASSAULT_RIFLE@Механизм штурмовой винтовки должен быть по-настоящему безотказным, подгоните детали друг к другу как можно тщательней на токарном станке.@SK_SMALL_GUNS 100&SK_REPAIR 100@SK_SMALL_GUNS 140&SK_REPAIR 130@PID_PUMP_PARTS 4&PID_FIREWOOD 2&PID_STEEL 1&PID_TUBE 1&PID_METAL_TRASH 6&PID_5MM_AP 12|PID_5MM_JHP 12@PID_MANUFACT_LATHE_INV 1&PID_MULTI_TOOL 1&PID_GUNS_AND_BULLETS 1&PID_COMBAT_KNIFE 1@PID_ASSAULT_RIFLE 1@exp 325 script fix_boy@fix_AssaultRifle }
{320}{}{PID_FN_FAL@Штурмовая винтовка – прекрасная база для того, чтобы на ее основе создать смертоносное оружие.@SK_SMALL_GUNS 120&SK_REPAIR 100@SK_SMALL_GUNS 150&SK_REPAIR 140@PID_ASSAULT_RIFLE 1&PID_PUMP_PARTS 3&PID_METAL_TRASH 4&PID_LUBRICANT 1&PID_7_62MM_AMMO 20@PID_MANUFACT_LATHE_INV 1&PID_MULTI_TOOL 1&PID_GUNS_AND_BULLETS 1@PID_FN_FAL 1@exp 360 script fix_boy@fix_FNFal }
{321}{}{PID_SNIPER_RIFLE@Превращение простенькой охотничьей винтовки в грозное оружие, способное загнать пулю в зад брамину с максимальной дистанции, под силу не каждому мастеру. Постарайтесь выточить все детали на токарном станке без единого изъяна.@SK_SMALL_GUNS 150&SK_REPAIR 140@SK_SMALL_GUNS 180&SK_REPAIR 165&SK_SCIENCE 100@PID_HUNTING_RIFLE 1&PID_STEEL 4&PID_POLYMER 2&PID_PUMP_PARTS 5&PID_METAL_TRASH 12&PID_OPTIKAL_SIGHT 1&PID_223_FMJ 15@PID_MANUFACT_LATHE_INV 1&PID_SUPER_TOOL_KIT 1&PID_GUNS_AND_BULLETS 1&PID_OIL_CAN_TRUE 1@PID_SNIPER_RIFLE 1@exp 1250 script fix_boy@fix_SniperRifle }
{322}{}{PID_TOMMY_GUN@За более, чем трехсотлетнюю историю, это оружие не утратило своего шарма. Разгуливая с таким по Пустоши, можно по праву называть себя гангстером, требуя дань с шлюх, наркодилеров и барыг.@SK_SMALL_GUNS 80&SK_REPAIR 70@SK_SMALL_GUNS 130&SK_REPAIR 100@PID_PUMP_PARTS 5&PID_FIREWOOD 3&PID_TUBE 1&PID_STEEL 2&PID_METAL_TRASH 7&PID_45_CALIBER_AMMO 25@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1&PID_GUNS_AND_BULLETS 1&PID_COMBAT_KNIFE 1@PID_TOMMY_GUN 1@exp 375 script fix_boy@fix_TommyGun }
{323}{}{PID_GREASE_GUN@Этот ПП не зря прозвали «жирной пушкой», позаботьтесь, чтобы он был смазан действительно хорошо во избежание заклиниваний механизма. Корпус изготавливайте на токарном станке из цельных листов металла.@SK_SMALL_GUNS 120&SK_REPAIR 100@SK_SMALL_GUNS 140&SK_REPAIR 125@PID_PUMP_PARTS 5&PID_TUBE 1&PID_STEEL 2&PID_METAL_TRASH 8&PID_LUBRICANT 2&PID_45_CALIBER_AMMO 30@PID_MANUFACT_LATHE_INV 1&PID_MULTI_TOOL 1&PID_GUNS_AND_BULLETS 1@PID_GREASE_GUN 1@exp 400 script fix_boy@fix_GreaseGun }
{324}{}{PID_223_PISTOL@Интеграция револьверного барабана в винтовку, да ещё и не того калибра - непростая задача, но в результат можно будет влюбиться.@SK_SMALL_GUNS 130&SK_REPAIR 110@SK_REPAIR 150&SK_SMALL_GUNS 160&SK_SCIENCE 80@PID_HUNTING_RIFLE 1&PID_44_MAGNUM_REVOLVER 1&PID_WELDING 1&PID_METAL_TRASH 5&PID_PUMP_PARTS 2@PID_MANUFACT_LATHE_INV 1&PID_SUPER_TOOL_KIT 1&PID_GUNS_AND_BULLETS 1&PID_OIL_CAN_TRUE 1@PID_223_PISTOL 1@exp 775 script fix_boy@fix_223Pistol }
{325}{}{PID_HK_G11@Выточите корпус на токарном станке из цельного полимерного блока. Собрав в нем уникальную схему механизма безгильзовой стрельбы, вы получите одно из самых выдающихся оружий XX века.@SK_REPAIR 140&SK_SMALL_GUNS 140&SK_SCIENCE 80@SK_REPAIR 155&SK_SMALL_GUNS 165&SK_SCIENCE 100@PID_METAL_TRASH 14&PID_STEEL 4&PID_TUBE 1&PID_PUMP_PARTS 6&PID_POLYMER 3&PID_OPTIKAL_SIGHT 1&PID_4_7MM_CASELESS 25@PID_PROD_PLANT1_INV 1&PID_SUPER_TOOL_KIT 1&PID_GUNS_AND_BULLETS 1&PID_OIL_CAN_TRUE 1@PID_HK_G11 1@exp 800 script fix_boy@fix_HKG11 }
{326}{}{PID_HK_G11E@Совершенству нет предела! Одна из статей в «Пушки и пули» наводит вас на мысли, что даже механизм г11 можно улучшить,  увеличив начальную скорость пули.@SK_REPAIR 140&SK_SMALL_GUNS 140&SK_SCIENCE 80@SK_REPAIR 180&SK_SMALL_GUNS 180&SK_SCIENCE 120@PID_HK_G11 1&PID_METAL_TRASH 3&PID_PUMP_PARTS 2&PID_V15_COMPUTER_PART 3&PID_ELECTRONIC_WASTE 2@PID_PROD_PLANT1_INV 1&PID_SUPER_TOOL_KIT 1&PID_GUNS_AND_BULLETS 1@PID_HK_G11E 1@exp 500 script fix_boy@fix_HKG11e }
{327}{}{PID_NEEDLER_PISTOL@Совместив познания в области легкого оружия и медицины, можно смастерить пневматический пистолет, стреляющий иглами для подкожных инъекций.@SK_REPAIR 100&SK_DOCTOR 60@SK_REPAIR 140&SK_SMALL_GUNS 90&SK_DOCTOR 115@PID_METAL_TRASH 2&PID_PUMP_PARTS 4&PID_TUBE 1&PID_POLYMER 1@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1&PID_GUNS_AND_BULLETS 1@PID_NEEDLER_PISTOL 1@exp 400 script fix_boy@fix_NeedlerPistol }
{328}{}{PID_PK12_GAUSS_PISTOL@Воспользуйтесь высокотехнологичной установкой, чтобы собрать последовательность из нескольких электромагнитов, разгоняющих металло-керамические шарики до невероятной скорости. Вы должны быть настоящим гением в области точных наук, чтобы запрограммировать установку правильно.@SK_REPAIR 150&SK_SMALL_GUNS 140&SK_SCIENCE 100@SK_REPAIR 180&SK_SMALL_GUNS 200&SK_SCIENCE 150@PID_METAL_TRASH 12&PID_PUMP_PARTS 5&PID_V15_COMPUTER_PART 10&PID_ELECTRO_MAGNET 3&PID_METAL_CERAMICS 2&PID_ELECTRONIC_WASTE 4&PID_STEEL 3&PID_2MM_EC_AMMO 10&PID_MICRO_FUSION_CELL 50@PID_PROD_PLANT1_INV 1&PID_SUPER_TOOL_KIT 1&PID_OIL_CAN_TRUE 1&PID_GUNS_AND_BULLETS 1&PID_DEANS_ELECTRONICS 1&PID_BIG_BOOK_OF_SCIENCE 1@PID_PK12_GAUSS_PISTOL 1@exp 1875 script fix_boy@fix_PK12GaussPistol }
{329}{}{PID_M72_GAUSS_RIFLE@Удлинение ствола орудия и увеличение количества электромагнитов благоприятно скажется на скорости пули, противники будут удивляться аккуратным дырочкам в своих телах.@SK_REPAIR 160&SK_SMALL_GUNS 175&SK_SCIENCE 120@SK_REPAIR 200&SK_SMALL_GUNS 220&SK_SCIENCE 180@PID_PK12_GAUSS_PISTOL 1&PID_METAL_TRASH 15&PID_ELECTRO_MAGNET 4&PID_METAL_CERAMICS 3&PID_PUMP_PARTS 5&PID_V15_COMPUTER_PART 12&PID_ELECTRONIC_WASTE 6&PID_2MM_EC_AMMO 10&PID_MICRO_FUSION_CELL 50@PID_PROD_PLANT2_INV 1&PID_SUPER_TOOL_KIT 1&PID_OIL_CAN_TRUE 1&PID_GUNS_AND_BULLETS 1&PID_DEANS_ELECTRONICS 1&PID_BIG_BOOK_OF_SCIENCE 1@PID_M72_GAUSS_RIFLE 1@exp 2300 script fix_boy@fix_M72GaussRifle }
{330}{}{PID_6_SHOT_PISTOL@Шесть стволов лучше, чем один! Просто подберите еще пяток труб подходящего размера, приделайте к каждой боек для одновременного выстрела из всех стволов и не забудьте вырезать рукоятку поудобнее.@@SK_REPAIR 50@PID_ZIP_GUN 1&PID_PUMP_PARTS 1&PID_METAL_TRASH 3&PID_10MM_JHP 6@@PID_6_SHOT_PISTOL 1@exp 220 script fix_boy@fix_AnyStuff1 }
{331}{}{PID_DOUBLE_10MM@В журнале «Пушки и Пули» описывается прекрасная возможность увеличить скорострельность вашего 10мм пистолета, путем монтирования второго ствола и доработки механизма подачи патронов.@SK_SMALL_GUNS 50&SK_REPAIR 50@SK_REPAIR 65&SK_SMALL_GUNS 75@PID_10MM_PISTOL 2&PID_METAL_TRASH 2&PID_PUMP_PARTS 1@PID_MULTI_TOOL 1@PID_DOUBLE_10MM 1@exp 150 script fix_boy@fix_AnyStuff2 }
{332}{}{PID_44_MAGNUM_SPEEDLOADER@В журнале «Пушки и Пули» описывается прекрасная возможность увеличить скорость перезарядки вашего револьвера при помощи специальной обоймы-спидлоадера.@SK_SMALL_GUNS 100&SK_REPAIR 80@SK_REPAIR 100&SK_SMALL_GUNS 115@PID_44_MAGNUM_REVOLVER 1&PID_SPEEDLOADER 1&PID_METAL_TRASH 1@PID_MULTI_TOOL 1&PID_GUNS_AND_BULLETS 1@PID_44_MAGNUM_SPEEDLOADER 1@exp 260 script fix_boy@fix_AnyStuff1 }
{333}{}{PID_HK_P90C@Расположите ударный механизм и магазин в прикладе, позади спускового крючка, существенно увеличив таким образом эффективную дальность стрельбы и убойность за счет удлинения ствола. Корпус выполните из легких полимеров.@SK_SMALL_GUNS 120&SK_REPAIR 120&SK_SCIENCE 60@SK_SMALL_GUNS 150&SK_REPAIR 150&SK_SCIENCE 80@PID_10MM_SMG  1&PID_PUMP_PARTS 6&PID_METAL_TRASH 8&PID_STEEL 3&PID_POLYMER 2&PID_10MM_JHP 24|PID_10MM_AP 24@PID_MANUFACT_LATHE_INV 1&PID_SUPER_TOOL_KIT 1&PID_OIL_CAN_TRUE 1&PID_GUNS_AND_BULLETS 1@PID_HK_P90C 1@exp 850 script fix_boy@fix_HKCaws }
{334}{}{PID_14MM_SMG@Вам кажется недостаточным того, что врагов охватывает первобытный страх при виде здоровенной дыры ствола 14мм пистолета? Приделайте к нему систему автоматики по принципу отвода пороховых газов и сможете делать из людей пюре.@SK_SMALL_GUNS 100&SK_REPAIR 100@SK_REPAIR 140&SK_SMALL_GUNS 140@PID_14MM_PISTOL 1&PID_METAL_TRASH 3&PID_PUMP_PARTS 2&PID_TUBE 1&PID_LUBRICANT 1&PID_14MM_AP 12@PID_MANUFACT_LATHE_INV 1&PID_MULTI_TOOL 1&PID_GUNS_AND_BULLETS 1@PID_14MM_SMG 1@exp 300 script fix_boy@fix_AssaultRifle }
{335}{}{PID_TBK_SMG@Соберите прогрессивный пистолет-пулемет в схеме буллпап с вертикально-скользящим затвором, что позволит максимально уменьшить длину ствольной коробки.@SK_SMALL_GUNS 80&SK_REPAIR 80@SK_REPAIR 140&SK_SMALL_GUNS 110@PID_PUMP_PARTS 7&PID_TUBE 1&PID_METAL_TRASH 5&PID_STEEL 1&PID_7_62MM_AMMO 12@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1&PID_GUNS_AND_BULLETS 1@PID_TBK_SMG 1@exp 325 script fix_boy@fix_AssaultRifle }
{336}{}{PID_9MM_SMG@Удивительная статья в «Пушках и пулях» рассказывает о том, как собрать простейший пистолет-пулемет всего из 47 деталей. А получится ли у вас?@SK_SMALL_GUNS 80&SK_REPAIR 60@SK_REPAIR 90&SK_SMALL_GUNS 100@PID_PUMP_PARTS 4&PID_STEEL 1&PID_TUBE 1&PID_METAL_TRASH 6&PID_LUBRICANT 1&PID_9MM_BALL 10|PID_9MM_AMMO 10@PID_MANUFACT_LATHE_INV 1&PID_MULTI_TOOL 1&PID_GUNS_AND_BULLETS 1@PID_9MM_SMG 1@exp 325 script fix_boy@fix_AssaultRifle }
{337}{}{PID_NAILGUN@Создание гвоздемёта потребует от вас хорошего навыка ремонта и немного фантазии. Механизм не требователен к материалам и оборудованию, все что вам необходимо, это верстак и стандартный набор инструментов.@SK_REPAIR 70@SK_REPAIR 100@PID_PUMP_PARTS 3&PID_METAL_TRASH 1&PID_NAILS 20&PID_SMALL_ENERGY_CELL 2@PID_MULTI_TOOL 1@PID_NAILGUN 1@exp 150 script fix_boy@fix_AnyStuff2 }
{338}{}{PID_HK_G36@Запрограммируйте ЧПУ станок на сборку высокоэффективной штурмовой винтовки H&K G36.@SK_REPAIR 150&SK_SMALL_GUNS 150&SK_SCIENCE 115@SK_REPAIR 185&SK_SMALL_GUNS 195&SK_SCIENCE 125@PID_METAL_TRASH 22&PID_STEEL 10&PID_TUBE 1&PID_PUMP_PARTS 12&PID_POLYMER 6&PID_OPTIKAL_SIGHT 1&PID_MICRO_FUSION_CELL 25@PID_PROD_PLANT1_INV 1&PID_SUPER_TOOL_KIT 1&PID_GUNS_AND_BULLETS 1&PID_OIL_CAN_TRUE 1@PID_HK_G36 1@exp 1350 script fix_boy@fix_G36 }
{339}{}{PID_INDEPENDENT@Запрограммируйте ЧПУ станок на сборку экпериментальной штурмовой винтовки XL70E3.@SK_REPAIR 140&SK_SMALL_GUNS 150&SK_SCIENCE 100@SK_REPAIR 175&SK_SMALL_GUNS 185&SK_SCIENCE 115@PID_METAL_TRASH 18&PID_STEEL 7&PID_TUBE 1&PID_PUMP_PARTS 11&PID_POLYMER 5&PID_OPTIKAL_SIGHT 1&PID_MICRO_FUSION_CELL 25@PID_PROD_PLANT1_INV 1&PID_SUPER_TOOL_KIT 1&PID_GUNS_AND_BULLETS 1&PID_OIL_CAN_TRUE 1@PID_INDEPENDENT 1@exp 1200 script fix_boy@fix_Independent }







#Тяжёлое

{400}{}{PID_FLAMER@Одним сварочным аппаратом совершаем магическое превращение груды металла в тело огнемёта, а вторым привариваем горелку и систему подачи топлива первого к этой конструкции.@SK_BIG_GUNS 40&SK_REPAIR 50@SK_REPAIR 70&SK_SCIENCE 50&SK_BIG_GUNS 60@PID_WELDING 1&PID_STEEL 2&PID_METAL_TRASH 4&PID_TUBE 1&PID_PUMP_PARTS 5@PID_MULTI_TOOL 1@PID_FLAMER 1@exp 460 script fix_boy@fix_AnyStuff3 }
{401}{}{PID_IMPROVED_FLAMETHROWER@Получив новый опыт в механике, вы поняли, что систему подачи топлива и сопло можно было бы переделать, чтобы уменьшить разбрызгивание топлива.@SK_BIG_GUNS 70&SK_REPAIR 70@SK_SCIENCE 70&SK_REPAIR 100&SK_BIG_GUNS 100@PID_PUMP_PARTS 3&PID_METAL_TRASH 5&PID_WELDING 1&PID_FLAMER 1&PID_FLAMETHROWER_FUEL 5@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1@PID_IMPROVED_FLAMETHROWER 1@exp 300 script fix_boy@fix_ImprovedFlamer }
{402}{}{PID_MINIGUN@Ваших небольших познаний в устройстве огнестрельного оружия хватит, чтобы собрать простейшую схему минигана Роквелла. Соберите механизм автоматического вращения шести стволов, представляющих собой 6 сваренных между собой труб подходящего диаметра, на основе отвода пороховых газов. Такая бандура способна напугать противника одним своим видом.@SK_BIG_GUNS 60&SK_REPAIR 80@SK_SCIENCE 60&SK_REPAIR 110&SK_BIG_GUNS 110@PID_PUMP_PARTS 4&PID_METAL_TRASH 8&PID_TUBE 3&PID_WELDING 1&PID_LUBRICANT 1&PID_5MM_AP 40|PID_5MM_JHP 40@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1@PID_MINIGUN 1@exp 500 script fix_boy@fix_Minigun }
{403}{}{PID_AVENGER_MINIGUN@Здоровая черная пушка. Вертится, жужжит, несет смерть. Небольшие улучшения, тщательная подгонка деталей, использование гелиевого охлаждения и хромирование стволов превращают кустарно сделанный шестиствольник в оружие для жесткого подавления живой силы противника на больших дистанциях.@SK_BIG_GUNS 120&SK_REPAIR 100@SK_SCIENCE 80&SK_REPAIR 140&SK_BIG_GUNS 150@PID_PUMP_PARTS 4&PID_METAL_TRASH 8&PID_ELECTRONIC_WASTE 2&PID_STEEL 3&PID_WELDING 2&PID_MINIGUN 1&PID_5MM_AP 40|PID_5MM_JHP 40@PID_MANUFACT_LATHE_INV 1&PID_SUPER_TOOL_KIT 1&PID_BOOK_OF_HEAVY_WEAPON 1@PID_AVENGER_MINIGUN 1@exp 800 script fix_boy@fix_AvengerMinigun }
{404}{}{PID_VINDICATOR_MINIGUN@Идя по стопам немецкой компании «Рейнметал АГ», запрограммировав станок на изготовление шести карбон-полимерных стволов и высокопрочных частей газоотводного механизма, вы получите венец эволюции шестиствольных пулеметов. Некоторые готовые части механизма безгильзовой стрельбы можно взять от Г11.@SK_BIG_GUNS 150&SK_REPAIR 150&SK_SCIENCE 120@SK_SCIENCE 150&SK_REPAIR 200&SK_BIG_GUNS 200@PID_PUMP_PARTS 5&PID_METAL_TRASH 18&PID_STEEL 5&PID_CARBON 6&PID_METAL_CERAMICS 3&PID_V15_COMPUTER_PART 7&PID_ELECTRONIC_WASTE 6&PID_WELDING 4&PID_4_7MM_CASELESS 150&PID_ROBOT_MOTIVATOR 1&PID_MICRO_FUSION_CELL 75&PID_HK_G11 3@PID_PROD_PLANT2_INV 1&PID_SUPER_TOOL_KIT 1&PID_BOOK_OF_HEAVY_WEAPON 1&PID_DEANS_ELECTRONICS 1&PID_OIL_CAN_TRUE 1@PID_VINDICATOR_MINIGUN 1@exp 3500 script fix_boy@fix_VindicatorMinigun }
{405}{}{PID_M60@Армейский журнал утверждает, что собрать этот прославленный в довоенные годы пулемет можно используя минимум инструментов. Но достаточно ли у вас прямые руки?@SK_BIG_GUNS 100&SK_REPAIR 80@SK_REPAIR 120&SK_BIG_GUNS 140@PID_PUMP_PARTS 2&PID_METAL_TRASH 10&PID_STEEL 2&PID_TUBE 1&PID_WELDING 1&PID_7_62MM_AMMO 10@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1&PID_BOOK_OF_HEAVY_WEAPON 1@PID_M60 1@exp 420 script fix_boy@fix_M60 }
{406}{}{PID_LIGHT_SUPPORT_WEAPON@Модифицирование пулемета М60 под более убойный калибр .223 и переработка откровенно ненадежной затворной группы и газоотводного узла позволит вам использовать потенциал этого оружия в полной мере.@SK_BIG_GUNS 120&SK_REPAIR 120@SK_REPAIR 150&SK_BIG_GUNS 160@PID_M60 1&PID_PUMP_PARTS 3&PID_METAL_TRASH 6&PID_STEEL 2&PID_TUBE 1&PID_WELDING 2&PID_FIREWOOD 3&PID_LUBRICANT 1&PID_223_FMJ 60@PID_MANUFACT_LATHE_INV 1&PID_MULTI_TOOL 1&PID_BOOK_OF_HEAVY_WEAPON 1@PID_LIGHT_SUPPORT_WEAPON 1@exp 550 script fix_boy@fix_LightSupportWeapon }
{407}{}{PID_BOZAR@Уникальный пулемет, являющийся венцом снайперского искусства. Даже армейский шлем не помешает пуле, выпущенной из Бозара, превратить мозг вашего противника в гребанное пюре.@SK_BIG_GUNS 170&SK_REPAIR 150@SK_SCIENCE 100&SK_REPAIR 200&SK_BIG_GUNS 220@PID_SNIPER_RIFLE 1&PID_LIGHT_SUPPORT_WEAPON 1&PID_PUMP_PARTS 5&PID_METAL_TRASH 14&PID_STEEL 5&PID_POLYMER 6&PID_METAL_CERAMICS 4&PID_WELDING 2&PID_223_FMJ 120&PID_MICRO_FUSION_CELL 75@PID_PROD_PLANT1_INV 1&PID_SUPER_TOOL_KIT 1&PID_GUNS_AND_BULLETS 1&PID_BOOK_OF_HEAVY_WEAPON 1&PID_OIL_CAN_TRUE 1@PID_BOZAR 1@exp 3325 script fix_boy@fix_Bozar }
{408}{}{PID_ROCKET_LAUNCHER@Самый распространенный ПРК, и, одновременно, представитель одной из небольшого количества моделей, предназначенных для стрельбы с плеча и имеющий возможность перезарядки.@SK_BIG_GUNS 100&SK_REPAIR 100@SK_SCIENCE 70&SK_REPAIR 140&SK_BIG_GUNS 150@PID_PUMP_PARTS 4&PID_METAL_TRASH 6&PID_STEEL 6&PID_WELDING 3&PID_EXPLOSIVE_ROCKET 1|PID_ROCKET_AP 1@PID_MANUFACT_LATHE_INV 1&PID_MULTI_TOOL 1&PID_BOOK_OF_HEAVY_WEAPON 1@PID_ROCKET_LAUNCHER 1@exp 700 script fix_boy@fix_RocketLauncher }
{409}{}{PID_FLAMER_MK3@Изучение научной литературы принесло свои плоды  - теперь вы можете прикрутить электронную систему разбрызгивания топлива  для увеличения давления струи,а значит - уменьшения его затрат, сохранив прежний урон.@SK_BIG_GUNS 100&SK_REPAIR 120&SK_SCIENCE 100@SK_SCIENCE 120&SK_REPAIR 150&SK_BIG_GUNS 120@PID_PUMP_PARTS 3&PID_METAL_TRASH 5&PID_WELDING 2&PID_ELECTRONIC_WASTE 3&PID_IMPROVED_FLAMETHROWER 1&PID_FLAMETHROWER_FUEL 8@PID_WORKBENCH_INV 1&PID_SUPER_TOOL_KIT 1&PID_DEANS_ELECTRONICS 1@PID_FLAMER_MK3 1@exp 500 script fix_boy@fix_ImprovedFlamer }
{410}{}{PID_GRANADE_PISTOL@Толстая труба, крепкий спусковой механизм и удобная рукоять - получите, блядь, 40мм пистолет.@SK_BIG_GUNS 75&SK_REPAIR 75@SK_REPAIR 90&SK_BIG_GUNS 120@PID_TUBE 1&PID_STEEL 1&PID_METAL_TRASH 3&PID_FIREWOOD 1&PID_PUMP_PARTS 2&PID_40MM_GRANADE 1@PID_MULTI_TOOL 1@PID_GRANADE_PISTOL 1@exp 275 script fix_boy@fix_AnyStuff2 }
{411}{}{PID_REVOLV_GRENADE@Добавьте барабанный магазин и  затвор для подачи гранат в ствол и разбрасываться гранатами станет куда удобнее.@SK_REPAIR 160&SK_BIG_GUNS 120@SK_REPAIR 185&SK_BIG_GUNS 150@PID_GRANADE_REVOLV_I 1&PID_STEEL 3&PID_METAL_TRASH 8&PID_FIREWOOD 2&PID_PUMP_PARTS 6&PID_WELDING 2&PID_40MM_GRANADE 3@PID_MANUFACT_LATHE_INV 1&PID_MULTI_TOOL 1&PID_BOOK_OF_HEAVY_WEAPON 1@PID_REVOLV_GRENADE 1@exp 550 script fix_boy@fix_RocketLauncher }
{412}{}{PID_MORTAR@Подготовьте идеальную форму и по рецепту средневековых мастеров отлейте разрушительное стальное орудие эпохи давно забытых времен.@SK_REPAIR 125&SK_BIG_GUNS 120@SK_REPAIR 195&SK_BIG_GUNS 150&SK_SCIENCE 100@PID_TUBE 1&PID_STEEL 22&PID_METAL_TRASH 8&PID_FIREWOOD 8&PID_PUMP_PARTS 6&PID_WELDING 12&PID_CANNON_BALLS 3@PID_MANUFACT_LATHE_INV 1&PID_BOOK_OF_HEAVY_WEAPON 1&PID_SUPER_TOOL_KIT 1@PID_MORTAR 1@exp 1500 script fix_boy@fix_RocketLauncher }
{413}{}{PID_GRANADE_REVOLV_I@Приварите по одному толстому куску трубы к стволам, желательно идентичных диаметров, сделайте простой затвор для подачи гранат в стволы, и сможете посылать гранаты не только дальше и эффективнее, но и дуплетом.@SK_REPAIR 90@SK_REPAIR 125&SK_BIG_GUNS 130@PID_GRANADE_PISTOL 2&PID_TUBE 2&PID_STEEL 2&PID_METAL_TRASH 6&PID_PUMP_PARTS 4&PID_WELDING 1@PID_MULTI_TOOL 1&PID_BOOK_OF_HEAVY_WEAPON 1@PID_GRANADE_REVOLV_I 1@exp 600 script fix_boy@fix_GranadeRevolvI }
{414}{}{PID_14MM_MACHINEGUN@Вдохновляясь статьей из оружейного журнала, соорудите сплит систему из двух 14 мм пистолет-пулеметов. Теперь неважно, во что одет противник, на нем останутся одни лохмотья.@SK_BIG_GUNS 80&SK_REPAIR 80@SK_SCIENCE 40&SK_REPAIR 125&SK_BIG_GUNS 140@PID_14MM_SMG 2&PID_PUMP_PARTS 5&PID_METAL_TRASH 4&PID_STEEL 2&PID_WELDING 1&PID_14MM_AP 22@PID_MANUFACT_LATHE_INV 1&PID_MULTI_TOOL 1&PID_BOOK_OF_HEAVY_WEAPON 1@PID_14MM_MACHINEGUN 1@exp 450 script fix_boy@fix_LightSupportWeapon }






#Энерго

{500}{}{PID_LASER_PISTOL@Комбинация простого лазерного целеуказателя с хорошими конденсаторами и источником энергии может сделать его вполне реальным оружием.@SK_ENERGY_WEAPONS 50@SK_SCIENCE 80&SK_REPAIR 60&SK_ENERGY_WEAPONS 70@PID_10MM_PISTOL 1&PID_METAL_TRASH 3&PID_PUMP_PARTS 2&PID_V15_COMPUTER_PART 1&PID_ELECTRONIC_WASTE 1@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1&PID_DEANS_ELECTRONICS 1@PID_LASER_PISTOL 1@exp 350 script fix_boy@fix_LaserPistol }
{501}{}{PID_MAGNETO_LASER_PISTOL@Установка специальных магнитов вокруг рубинового стержня уплотнит поток боевых фотонов.@SK_ENERGY_WEAPONS 70@SK_ENERGY_WEAPONS 100&SK_SCIENCE 110&SK_REPAIR 80@PID_LASER_PISTOL 1&PID_V15_COMPUTER_PART 2&PID_ELECTRONIC_WASTE 1&PID_PUMP_PARTS 4@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_DEANS_ELECTRONICS 1@PID_MAGNETO_LASER_PISTOL 1@exp 350 script fix_boy@fix_MagnetoLaserPistol }
{502}{}{PID_LASER_RIFLE@Сфокусируйте лазерные лучи от пары целеуказателей, добавьте источник энергии помощнее и сможете распиливать ваших врагов еще до того, как они поймут что происходит.@SK_ENERGY_WEAPONS 100&SK_SCIENCE 80@SK_REPAIR 120&SK_SCIENCE 140&SK_ENERGY_WEAPONS 140@PID_LASER_PISTOL 2&PID_V15_COMPUTER_PART 3&PID_ELECTRONIC_WASTE 2&PID_PUMP_PARTS 5&PID_METAL_TRASH 8&PID_TUBE 1&PID_STEEL 1&PID_WELDING 1@PID_MANUFACT_LATHE_INV 1&PID_MULTI_TOOL 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_DEANS_ELECTRONICS 1@PID_LASER_RIFLE 1@exp 510 script fix_boy@fix_LaserRifle }
{503}{}{PID_LASER_RIFLE_EXT_CAP@После изучения технической литературы вы понимаете, что заводскую сборку можно очень сильно оптимизировать. Время поработать паяльником!@SK_ENERGY_WEAPONS 120&SK_SCIENCE 120@SK_REPAIR 135&SK_SCIENCE 170&SK_ENERGY_WEAPONS 140@PID_LASER_RIFLE 1&PID_V15_COMPUTER_PART 5&PID_ELECTRONIC_WASTE 2&PID_PUMP_PARTS 4&PID_METAL_TRASH 2@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_DEANS_ELECTRONICS 1@PID_LASER_RIFLE_EXT_CAP 1@exp 500 script fix_boy@fix_LaserRifleExtCap }
{504}{}{PID_PLASMA_PISTOL@Вмонтируйте в корпус крупнокалиберного пистолета плазменный трансформатор, генерирующий сгустки высокотемпературной плазмы. Электромагнитное поле придаст им необходимое ускорение.@SK_ENERGY_WEAPONS 100&SK_SCIENCE 110@SK_SCIENCE 130&SK_ENERGY_WEAPONS 120&SK_REPAIR 100@PID_14MM_PISTOL 1&PID_PLASMA_TRANSFORMER 1&PID_V15_COMPUTER_PART 3&PID_ELECTRONIC_WASTE 2&PID_PUMP_PARTS 3&PID_METAL_TRASH 4@PID_MANUFACT_LATHE_INV 1&PID_MULTI_TOOL 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_DEANS_ELECTRONICS 1&PID_BOOK_OF_ENERGY_WEAPON 1@PID_PLASMA_PISTOL 1@exp 450 script fix_boy@fix_PlasmaPistol }
{505}{}{PID_PLASMA_PISTOL_EXT_CART@Отключить к чёрту системы охлаждения, и пистолет будет расходовать меньше энергии. Правда, стрелять придётся в перчатках.@SK_REPAIR 100&SK_SCIENCE 110@SK_SCIENCE 160&SK_REPAIR 140@PID_PLASMA_PISTOL 1&PID_V15_COMPUTER_PART 2&PID_PUMP_PARTS 4&PID_ELECTRONIC_WASTE 1@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_DEANS_ELECTRONICS 1@PID_PLASMA_PISTOL_EXT_CART 1@exp 450 script fix_boy@fix_PlasmaPistolExtCart }
{506}{}{PID_PLASMA_RIFLE@Соедините параллельно схемы из нескольких плазменных пистолетов в корпусе лазерной винтовки, чтобы создавать более горячий и крупный плазменный сгусток. Придется позаботиться о хорошей системе охлаждения.@SK_SCIENCE 150&SK_ENERGY_WEAPONS 120@SK_SCIENCE 175&SK_ENERGY_WEAPONS 150&SK_REPAIR 160@PID_LASER_RIFLE 1&PID_WELDING 3&PID_V15_COMPUTER_PART 10&PID_PUMP_PARTS 6&PID_ELECTRONIC_WASTE 6&PID_METAL_TRASH 8&PID_MICRO_FUSION_CELL 40&PID_PLASMA_PISTOL 3@PID_PROD_PLANT1_INV 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_DEANS_ELECTRONICS 1&PID_SUPER_TOOL_KIT 1&PID_BOOK_OF_ENERGY_WEAPON 1@PID_PLASMA_RIFLE 1@exp 1000 script fix_boy@fix_PlasmaRifle }
{507}{}{PID_TURBO_PLASMA_RIFLE@Вы бы никогда не поверили, что тепловая обмотка может ускорить формирование заряда, но так было написано в книжке. И вот он результат!@SK_SCIENCE 140&SK_ENERGY_WEAPONS 150@SK_SCIENCE 180&SK_ENERGY_WEAPONS 170&SK_REPAIR 180@PID_PLASMA_RIFLE 1&PID_WELDING 1&PID_ELECTRONIC_WASTE 3&PID_V15_COMPUTER_PART 5&PID_ELECTRO_MAGNET 1&PID_PUMP_PARTS 3&PID_METAL_TRASH 3@PID_WORKBENCH_INV 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_DEANS_ELECTRONICS 1&PID_BOOK_OF_ENERGY_WEAPON 1&PID_SUPER_TOOL_KIT 1@PID_TURBO_PLASMA_RIFLE 1@exp 1100 script fix_boy@fix_TurboPlasmaRifle }
{508}{}{PID_YK32_PULSE_PISTOL@Соберите в диэлектрическом корпусе электрическую схему с несколькими мощными конденсаторами и генератором импульсов, который, создав ионизированный воздушный туннель, доставит электричесий импульс до цели.@SK_ENERGY_WEAPONS 120&SK_SCIENCE 150@SK_SCIENCE 180&SK_ENERGY_WEAPONS 180&SK_REPAIR 175@PID_POLYMER 4&PID_ELECTRONIC_WASTE 3&PID_V15_COMPUTER_PART 6&PID_PUMP_PARTS 7&PID_METAL_TRASH 5&PID_CAPACITOR 3&PID_IMPULSE_GENERATOR 1&PID_SMALL_ENERGY_CELL 50@PID_PROD_PLANT1_INV 1&PID_SUPER_TOOL_KIT 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_DEANS_ELECTRONICS 1&PID_BOOK_OF_ENERGY_WEAPON 1@PID_YK32_PULSE_PISTOL 1@exp 1550 script fix_boy@fix_YK32PulsePistol }
{509}{}{PID_YK42B_PULSE_RIFLE@Сверхпроводящий ствол плазменной винтовки отлично подойдёт для того, чтобы собирать и направлять заряд с конденсаторов трех импульсных пистолетов, а система энергопитания от ядерных микрореакторов - для того, чтобы их запитать.@SK_SCIENCE 180&SK_ENERGY_WEAPONS 160@SK_SCIENCE 200&SK_ENERGY_WEAPONS 200&SK_REPAIR 200@PID_PLASMA_RIFLE 1&PID_YK32_PULSE_PISTOL 3&PID_ELECTRONIC_WASTE 9&PID_METAL_TRASH 18&PID_V15_COMPUTER_PART 14&PID_SUPER_CAPACITOR 1&PID_PUMP_PARTS 10&PID_METAL_CERAMICS 5&PID_MICRO_FUSION_CELL 100@PID_PROD_PLANT1_INV 1&PID_SUPER_TOOL_KIT 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_DEANS_ELECTRONICS 1&PID_BOOK_OF_ENERGY_WEAPON 1@PID_YK42B_PULSE_RIFLE 1@exp 3500 script fix_boy@fix_YK42BPulseRifle }
{510}{}{PID_GATLING_LASER@Замените начинку "Авенджера" на боевую часть лазерной винтовки, а стволы заключите в обмотку из медной проволоки, сформировав на каждом электромагнит, который бы помогал фокусировать и уплотнять заряд.@SK_SCIENCE 180&SK_ENERGY_WEAPONS 180@SK_SCIENCE 200&SK_REPAIR 220&SK_ENERGY_WEAPONS 210@PID_AVENGER_MINIGUN 1&PID_LASER_RIFLE 6&PID_PUMP_PARTS 9&PID_ELECTRONIC_WASTE 11&PID_WELDING 4&PID_METAL_CERAMICS 4&PID_ELECTRO_MAGNET 3&PID_V15_COMPUTER_PART 18&PID_ROBOT_MOTIVATOR 1&PID_MICRO_FUSION_CELL 100@PID_PROD_PLANT2_INV 1&PID_SUPER_TOOL_KIT 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_DEANS_ELECTRONICS 1&PID_BOOK_OF_ENERGY_WEAPON 1@PID_GATLING_LASER 1@exp 4150 script fix_boy@fix_GatlingLaser }
{511}{}{PID_TESLA_PISTOL@Мощные конденсаторы и несколько генераторов импульсов, включенных параллельно, позволят послать к цели не просто элекрический импульс через ионизированный воздушный туннель, а миниатюрную молнию, сформированную катушками Теслы. Аккуратнее, миллионы вольт могут вернуться назад к вам, если находиться слишком близко к цели.@SK_ENERGY_WEAPONS 160&SK_SCIENCE 180@SK_SCIENCE 220&SK_ENERGY_WEAPONS 180&SK_REPAIR 200@PID_POLYMER 6&PID_ELECTRONIC_WASTE 10&PID_V15_COMPUTER_PART 12&PID_PUMP_PARTS 8&PID_METAL_TRASH 10&PID_CAPACITOR 3&PID_SUPER_CAPACITOR 1&PID_IMPULSE_GENERATOR 3&PID_METAL_CERAMICS 2&PID_SMALL_ENERGY_CELL 100@PID_PROD_PLANT1_INV 1&PID_SUPER_TOOL_KIT 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_DEANS_ELECTRONICS 1&PID_BOOK_OF_ENERGY_WEAPON 1@PID_TESLA_PISTOL 1@exp 2200 script fix_boy@fix_YK32PulsePistol }



#Медикаменты и электроника

{700}{}{PID_HEALING_POWDER@Разотрите камнем высушенные на солнце ингредиенты и заверните в тряпочку.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 40@PID_BROC_FLOWER 1&PID_XANDER_ROOT 1&PID_RAGS 1@PID_ROCK 1@PID_HEALING_POWDER 1@exp 75 script fix_boy@fix_AnyStuff1 }
{701}{}{PID_ANTIDOTE@Это будет скорее самовнушением.@SK_OUTDOORSMAN 30@SK_OUTDOORSMAN 40&SK_DOCTOR 30@PID_BOOZE 1&PID_SCORPION_TAIL 1@PID_LIGHTER 1@PID_ANTIDOTE 1@exp 75 script fix_boy@fix_AnyStuff1 }
{702}{}{PID_LOCKPICKS@Вы разбираетесь в этом деле и можете сами себе изготовить отмычки. В красивом кожаном чехле.@SK_LOCKPICK 20@SK_LOCKPICK 50&SK_REPAIR 50@PID_METAL_TRASH 1&PID_GECKO_PELT 1@PID_MULTI_TOOL 1&PID_BOOK_OF_LOCKPICKING 1@PID_LOCKPICKS 1@exp 100 script fix_boy@fix_AnyStuff1 }
{703}{}{PID_EXP_LOCKPICK_SET@Профессионалы вроде вас работают только с качественными инструментами!@SK_LOCKPICK 100@SK_LOCKPICK 150&SK_REPAIR 120@PID_LOCKPICKS 1&PID_METAL_TRASH 1&PID_PUMP_PARTS 1@PID_SUPER_TOOL_KIT 1&PID_BOOK_OF_LOCKPICKING 1@PID_EXP_LOCKPICK_SET 1@exp 300 script fix_boy@fix_AnyStuff1 }
{704}{}{PID_RADIO@Вам одиноко? Не с кем общаться? Вокруг одни сволочи и кротокрысы? Вам хочется об этом поговорить? Специально для вас! Схема простейшего приёмника в каждом номере "Электроники Дина"!@SK_SCIENCE 40@SK_SCIENCE 80&SK_REPAIR 50@PID_V15_COMPUTER_PART 1&PID_PUMP_PARTS 1&PID_METAL_TRASH 1@PID_MULTI_TOOL 1&PID_DEANS_ELECTRONICS 1@PID_RADIO 1@exp 150 script fix_boy@fix_AnyStuff1 }
{705}{}{PID_FIRST_AID_KIT@Бинты, спирт для промывки ран и другие полезные вещи в сумке из кожи многострадального гекко.@SK_FIRST_AID 50@SK_DOCTOR 50&SK_FIRST_AID 60&SK_SCIENCE 20@PID_RAGS 5&PID_BOOZE 1&PID_ANTIDOTE 1&PID_GECKO_PELT 1&PID_POCKET_LINT 1@@PID_FIRST_AID_KIT 1@exp 225 script fix_boy@fix_AnyStuff1 }
{706}{}{PID_RADIO@Почините радио с использованием деталей со старых микросхем.@SK_REPAIR 50@SK_REPAIR 60@PID_VIC_RADIO 1&PID_V15_COMPUTER_PART 1@PID_MULTI_TOOL 1@PID_RADIO 1@exp 260 script fix_boy@fix_AnyStuff1 }
{707}{}{PID_STIMPAK@Растворите целебный порошок в воде, наполните этой смесью стеклянный шприц и прокипятите. Потом простерилизуйте иглу спиртом.@SK_FIRST_AID 30@SK_FIRST_AID 80&SK_SCIENCE 50@PID_BOTTLE_FULL 1&PID_HYPODERMIC_NEEDLE 3&PID_BOOZE 1&PID_HEALING_POWDER 3@PID_LIGHTER 1&PID_FIRST_AID_BOOK 1@PID_STIMPAK 3&PID_RAGS 3@exp 200 script fix_boy@fix_AnyStuff2 }
{708}{}{PID_SUPER_STIMPAK@В химическом журнале описывается способ существенного усиления целебного потенциала стимпака. Основную роль тут сыграет вытяжка из браминьих кишок, способная сильно ускорить регенерацию тканей.@SK_FIRST_AID 100&SK_SCIENCE 80@SK_FIRST_AID 150&SK_DOCTOR 125&SK_SCIENCE 120@PID_STIMPAK 3&PID_MUTATED_FRUIT 2&PID_NUKA_COLA 1&PID_JUICE 1@PID_LIGHTER 1&PID_CHEMISTRY_MANUAL 1&PID_FIELD_MEDIC_KIT 1&PID_BOOK_OF_DOCTOR 1@PID_SUPER_STIMPAK 3@exp 300 script fix_boy@fix_AnyStuff2 }
{709}{}{PID_PSYCHO@Растолчите горстку псилоцибе полуланцетовидной и баффаут в порошок и растворите в пойле, добавьте химических веществ для подавления чувствительности нервных окончаний. Содержимое суперстимпака на время нивелирует вред здоровью от такой смеси.@SK_FIRST_AID 100&SK_SCIENCE 80&SK_DOCTOR 100@SK_FIRST_AID 150&SK_DOCTOR 180&SK_SCIENCE 175@PID_SUPER_STIMPAK 1&PID_MUSHROOM1 2&PID_ROT_GUT 1&PID_CHEMICALS 1&PID_BUFFOUT 1@PID_LIGHTER 1&PID_CHEMISTRY_MANUAL 1&PID_BOOK_OF_DOCTOR 1&PID_PARAMEDICS_BAG 1@PID_PSYCHO 1@exp 300 script fix_boy@fix_AnyStuff3 }
{710}{}{PID_HEALING_POWDER_MK2@Разотрите камнем высушенный на солнце браминий кишечник и добавьте в имеющийся целебный порошок.@SK_OUTDOORSMAN 40@SK_OUTDOORSMAN 60@PID_HEALING_POWDER 2&PID_INTESTINES_DRY 1@PID_ROCK 1@PID_HEALING_POWDER_MK2 2@exp 100 script fix_boy@fix_AnyStuff1 }
{711}{}{PID_HYPO@В химическом журнале описывается способ существенного усиления целебного потенциала суперстимпака путем перегонки вытяжки из браминьих кишок с определенными химикатами.@SK_FIRST_AID 100&SK_SCIENCE 80@SK_FIRST_AID 125&SK_DOCTOR 125&SK_SCIENCE 120@PID_SUPER_STIMPAK 3&PID_CHEMICALS 1&PID_JUICE 1&PID_FIREWOOD 1@PID_SAMOGON_INV 1&PID_LIGHTER 1&PID_CHEMISTRY_MANUAL 1&PID_FIELD_MEDIC_KIT 1&PID_BOOK_OF_DOCTOR 1@PID_HYPO 3@exp 300 script fix_boy@fix_Hyppo }
{712}{}{PID_BUFFOUT@Широкие познания в химии и медицине позволяют вам подбирать правильную комбинацию веществ, оказывающих требуемое воздействие на человеческое тело.@SK_DOCTOR 20@SK_DOCTOR 50&SK_SCIENCE 40@PID_CHEMICALS 1&PID_BOOZE 1&PID_MUSHROOM1 3&PID_MUSHROOM2 1&PID_FIREWOOD 1@PID_LIGHTER 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_BOOK_OF_DOCTOR 1&PID_SAMOGON_INV 1@PID_BUFFOUT 2@exp 150 script fix_boy@fix_Buffout }
{713}{}{PID_MENTATS@Широкие познания в химии и медицине позволяют вам подбирать правильную комбинацию веществ, оказывающих требуемое воздействие на человеческое тело.@SK_DOCTOR 30@SK_DOCTOR 50&SK_SCIENCE 40@PID_CHEMICALS 1&PID_NUKA_COLA 1&PID_MUSHROOM1 3&PID_MUSHROOM2 1&PID_FIREWOOD 1@PID_LIGHTER 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_BOOK_OF_DOCTOR 1&PID_SAMOGON_INV 1@PID_MENTATS 2@exp 150 script fix_boy@fix_Mentats }




# Взрывчатка

{800}{}{PID_TNT@Вливайте азотную кислоту в толуол, постоянно нагревая. Получившийся осадок просушите. Готово.@SK_SCIENCE 80@SK_SCIENCE 120@PID_CHEMICALS 2&PID_BOTTLE_FULL 1@PID_LIGHTER 1&PID_BIG_BOOK_OF_SCIENCE 1@PID_TNT 3@exp 175 script fix_boy@fix_AnyStuff1 }
{801}{}{PID_FRAG_GRENADE@Поместите взрывчатое вещевство в осколочную рубашку и придумайте простенький взрыватель.@SK_REPAIR 80@SK_REPAIR 100@PID_PUMP_PARTS 3&PID_METAL_TRASH 3&PID_TNT 2@PID_MULTI_TOOL 1&PID_BOOK_OF_EXPLOSIVE 1@PID_FRAG_GRENADE 3@exp 200 script fix_boy@fix_AnyStuff1 }
{802}{}{PID_PLASMA_GRENADE@Намотайте вокруг гранаты провод и подключите его к питанию, чтобы получился электромагнит. Выньте часть взрывчатого вещевства и изолируйте в образовавшемся пространстве небольшую полость. Автоматика поместит туда заряд плазмы.@SK_SCIENCE 80@SK_SCIENCE 120&SK_REPAIR 140@PID_PUMP_PARTS 1&PID_FRAG_GRENADE 1&PID_MICRO_FUSION_CELL 3@PID_WORKBENCH_INV_HUB 1&PID_MULTI_TOOL 1&PID_BIG_BOOK_OF_SCIENCE 1@PID_PLASMA_GRENADE 1@exp 75 script fix_boy@fix_PlasmaGrenade}
{803}{}{PID_NITROGLYCERIN@Отделите жир от мяса, смешивайте с азотной и серной кислотой для получения нитроглицерина. Следите за тем, чтобы смесь не перегревалась во время реакции.@SK_SCIENCE 50@SK_SCIENCE 80&SK_OUTDOORSMAN 80@PID_MEAT 3&PID_CHEMICALS 2&PID_BOTTLE_EMPTY 1@PID_BIG_BOOK_OF_SCIENCE 1@PID_NITROGLYCERIN 5@exp 200 script fix_boy@fix_AnyStuff1 }
{804}{}{PID_DYNAMITE@Смешайте нитроглицерин с порошком для получения клейкой массы. Перемешайте её с опилками, скатайте в цилиндры и дайте высохнуть. Присоедините взрыватель.@SK_TRAPS 50@SK_OUTDOORSMAN 30&SK_TRAPS 80&SK_REPAIR 60@PID_NITROGLYCERIN 1&PID_HEALING_POWDER 1&PID_FIREWOOD 1&PID_V15_COMPUTER_PART 1&PID_PUMP_PARTS 1@PID_MULTI_TOOL 1&PID_DEANS_ELECTRONICS 1&PID_BOOK_OF_EXPLOSIVE 1@PID_DYNAMITE 1@exp 150 script fix_boy@fix_AnyStuff1 }
{805}{}{PID_GUNPOWDER@Используйте кислоту для получения калийной селитры, смешайте 6 частей селитры с 1 частью угля и 1 серы.@SK_OUTDOORSMAN 40@SK_OUTDOORSMAN 60&SK_SCIENCE 90@PID_MINERAL 1&PID_CHEMICALS 1&PID_FIREWOOD 1@PID_BIG_BOOK_OF_SCIENCE 1&PID_ROCK 1@PID_GUNPOWDER 8@exp 180 script fix_boy@fix_AnyStuff1 }
{806}{}{PID_HEXOGEN@Получите нитрат аммония смешиванием собственной мочи с азотной кислотой и выпариванием. Добавьте толчёный буффаут. Залейте второй частью кислоты, охлаждайте, процедите осадок.@SK_SCIENCE 120@SK_SCIENCE 140&SK_OUTDOORSMAN 95@PID_BUFFOUT 1&PID_CHEMICALS 2&PID_BOTTLE_FULL 2&PID_RAGS 1@PID_LIGHTER 1&PID_CHEMISTRY_MANUAL 1@PID_HEXOGEN 3@exp 300 script fix_boy@fix_AnyStuff1 }
{807}{}{PID_PLASTIC_EXPLOSIVES_DULL@@SK_SCIENCE 120@SK_OUTDOORSMAN 90&SK_REPAIR 100&SK_SCIENCE 170@PID_PUMP_PARTS 1&PID_HEXOGEN 1@PID_LIGHTER 1&PID_CHEMISTRY_MANUAL 1&PID_BOOK_OF_EXPLOSIVE 1@PID_PLASTIC_EXPLOSIVES_DULL 1@exp 125 script fix_boy@fix_AnyStuff1 }
{808}{}{PID_PLASTIC_EXPLOSIVES@Соберите радиодетонатор из запчастей и старого радио.@SK_REPAIR 100@SK_REPAIR 130&SK_TRAPS 120@PID_PLASTIC_EXPLOSIVES_DULL 1&PID_PUMP_PARTS 1&PID_RADIO 1@PID_MULTI_TOOL 1&PID_DEANS_ELECTRONICS 1&PID_BOOK_OF_EXPLOSIVE 1@PID_PLASTIC_EXPLOSIVES 1@exp 220 script fix_boy@fix_AnyStuff1 }
{809}{}{PID_MINE@Высыпьте гексоген в какую-нибудь старую банку, соорудите простенький взрыватель с использованием капсюля ружейного патрона.@SK_TRAPS 80@SK_TRAPS 130&SK_REPAIR 150&SK_OUTDOORSMAN 75@PID_HEXOGEN 1&PID_PUMP_PARTS 2&PID_SHOTGUN_SHELLS 1@PID_MULTI_TOOL 1&PID_BOOK_OF_EXPLOSIVE 1@PID_MINE 1@exp 200 script fix_boy@fix_AnyStuff1 }


#Холодное и инструменты

{900}{}{PID_RING_BOXING_GLOVES@Сшейте шкуры и набейте их мягким мусором.@SK_UNARMED 20@SK_UNARMED 50&SK_OUTDOORSMAN 40@PID_GECKO_PELT 2&PID_POCKET_LINT 4@PID_SHIV 1@PID_RING_BOXING_GLOVES 1@exp 75 script fix_boy@fix_AnyStuff1 }
{901}{}{PID_RING_PLATED_BOXING_GLOVES@Перчатки с утяжелителем - правильный выбор для участника подпольных боёв. Главное - не оставляйте их без присмотра в раздевалке, иначе грозит дисквалификация.@SK_UNARMED 40@SK_UNARMED 50&SK_OUTDOORSMAN 50&SK_REPAIR 30@PID_RING_BOXING_GLOVES 1&PID_METAL_TRASH 2@PID_MULTI_TOOL 1@PID_RING_PLATED_BOXING_GLOVES 1@exp 100 script fix_boy@fix_AnyStuff1 }
{902}{}{PID_BRASS_KNUCKLES@Пробейте дырки для пальцев в подходящей железяке, сможете попугать кого-нибудь. Только в драку с такой ерундой лучше не лезть.@SK_UNARMED 30@SK_UNARMED 50&SK_REPAIR 20@PID_METAL_TRASH 1@PID_MULTI_TOOL 1@PID_BRASS_KNUCKLES 1@exp 50 script fix_boy@fix_AnyStuff1 }
{903}{}{PID_SPIKED_KNUCKLES@Гуманизм - это для слабых. Не пожалейте денег на сварку, чтобы приварить шипы к своему старому кастету. Четыре дырки в противнике того стоят.@SK_UNARMED 30&SK_REPAIR 20@SK_UNARMED 50&SK_REPAIR 30@PID_BRASS_KNUCKLES 1&PID_METAL_TRASH 1@PID_WELDING 1@PID_SPIKED_KNUCKLES 1@exp 85 script fix_boy@fix_AnyStuff1 }
{904}{}{PID_CATTLE_PROD@Смонтируйте на дубинке простенький электрошокер, и жить станет веселей. Можно трахать получившимся инструментом браминов в зад, а можно людей по голове.@SK_REPAIR 40&SK_SCIENCE 40@SK_REPAIR 100&SK_SCIENCE 80@PID_CLUB 1&PID_PUMP_PARTS 2&PID_SMALL_ENERGY_CELL 10&PID_V15_COMPUTER_PART 2&PID_ELECTRONIC_WASTE 2@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1&PID_DEANS_ELECTRONICS 1@PID_CATTLE_PROD 1@exp 460 script fix_boy@fix_CattleProd }
{905}{}{PID_SUPER_CATTLE_PROD@После изучения нужной литературы у вас появилась замечательная идея насчёт того, как можно увеличить мощность электрошокера, не испортив его.@SK_SCIENCE 100&SK_REPAIR 80@SK_SCIENCE 160&SK_REPAIR 160@PID_CATTLE_PROD 1&PID_V15_COMPUTER_PART 6&PID_PUMP_PARTS 8&PID_CAPACITOR 2&PID_ELECTRONIC_WASTE 4&PID_POLYMER 2&PID_MICRO_FUSION_CELL 40@PID_PROD_PLANT1_INV 1&PID_SUPER_TOOL_KIT 1&PID_DEANS_ELECTRONICS 1&PID_BIG_BOOK_OF_SCIENCE 1@PID_SUPER_CATTLE_PROD 1@exp 1900 script fix_boy@fix_SuperCattleProd }
{906}{}{PID_SUPER_SLEDGE@Сделайте из металлического кола прочную рукоять, выточите на станке ударные части из железок попрочнее и оснастите их накопителем кинетической энергии согласно схеме. По сути, это просто жёсткая пружина и запирающий механизм. Для надежности придется использовать сплав попрочнее.@SK_SCIENCE 80@SK_SCIENCE 140&SK_REPAIR 200@PID_METAL_TRASH 7&PID_PUMP_PARTS 4&PID_TUBE 2&PID_PLANK 1&PID_STEEL 2&PID_WELDING 2&PID_SMALL_ENERGY_CELL 50&PID_V15_COMPUTER_PART 4&PID_METAL_CERAMICS 2@PID_WORKBENCH_INV_SHOE 1&PID_SUPER_TOOL_KIT 1@PID_SUPER_SLEDGE 1@exp 2450 script fix_boy@fix_SuperSledge}
{907}{}{PID_WAKIZASHI_BLADE@Только человек, посвятивший себя изучению оружия, знает, как выковать настоящее лезвие.@SK_MELEE_WEAPONS 100@SK_MELEE_WEAPONS 150&SK_REPAIR 90&SK_OUTDOORSMAN 50@PID_FIREWOOD 5&PID_STEEL 3&PID_GECKO_PELT 1&PID_BOTTLE_FULL 3@PID_SLEDGEHAMMER 1&PID_BOOK_OF_KNIVES 1&PID_LIGHTER 1@PID_WAKIZASHI_BLADE 1@exp 480 script fix_boy@fix_AnyStuff3 }
{908}{}{PID_COMBAT_KNIFE@Закалить заново лезвие, заточить, обмотать рукоять кожей, и этот нож уже можно называть оружием.@SK_MELEE_WEAPONS 40@SK_OUTDOORSMAN 40&SK_REPAIR 40&SK_MELEE_WEAPONS 80@PID_KNIFE 1&PID_GECKO_PELT 1&PID_FIREWOOD 1@PID_SLEDGEHAMMER 1&PID_LIGHTER 1@PID_COMBAT_KNIFE 1@exp 120 script fix_boy@fix_AnyStuff1 }
{909}{}{PID_SLEDGEHAMMER@Насадите железяку потяжелее на палку покрепче.@@SK_OUTDOORSMAN 30@PID_PUMP_PARTS 1&PID_FIREWOOD 1@@PID_SLEDGEHAMMER 1@exp 50 script fix_boy@fix_AnyStuff1 }
{910}{}{PID_SPEAR@Привяжите нож к палке. Это даст вам целый метр преимущества и килограмм уверенности.@@SK_OUTDOORSMAN 20&SK_MELEE_WEAPONS 40@PID_KNIFE 1&PID_ROPE 1&PID_SHARPENED_POLE 1@@PID_SPEAR 1@exp 100 script fix_boy@fix_AnyStuff1 }
{911}{}{PID_SHARP_SPEAR@Заточка копья кремнем от фирмы "Морлис" позволит разрубать врагов им как алебардой.@SK_OUTDOORSMAN 20@SK_MELEE_WEAPONS 50&SK_OUTDOORSMAN 30@PID_SPEAR 1&PID_FLINT 1@@PID_SHARP_SPEAR 1@exp 60 script fix_boy@fix_AnyStuff1 }
{912}{}{PID_SHARPENED_POLE@Вжик-вжик, готово!@@@PID_FIREWOOD 1@PID_KNIFE 1|PID_AXE 1|PID_COMBAT_KNIFE 1|PID_THROWING_KNIFE 1@PID_SHARPENED_POLE 1@exp 40 script fix_boy@fix_AnyStuff1 }
{913}{}{PID_CROWBAR@Нежными ударами придайте трубе правильную форму.@@SK_REPAIR 30@PID_TUBE 1@PID_SLEDGEHAMMER 1@PID_CROWBAR 1@exp 50 script fix_boy@fix_AnyStuff1 }
{914}{}{PID_WRENCH@Найдите железку подходящего размера и выпилите из неё нечто, чем можно было бы откручивать гайки.@@SK_REPAIR 30@PID_METAL_TRASH 1@PID_MULTI_TOOL 1@PID_WRENCH 1@exp 50 script fix_boy@fix_AnyStuff1 }
{915}{}{PID_KNIFE@Заточите несколько железяк, обмотайте рукояти какой-нибудь тряпкой. Получится несколько отличных ножей.@@SK_OUTDOORSMAN 20@PID_METAL_TRASH 1&PID_RAGS 1@@PID_KNIFE 3@exp 50 script fix_boy@fix_AnyStuff1 }
{916}{}{PID_CLUB@Отломайте нахрен минимум треть этой палки, забейте камнем в один конец какой-нибудь утяжелитель. Отломаный кусок можно притарабанить в качестве дополнительной рукояти. Готово, можно пойти проломить кому-нибудь черепушку.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 40&SK_REPAIR 30@PID_SHARPENED_POLE 1&PID_PUMP_PARTS 1@PID_ROCK 1@PID_CLUB 1@exp 60 script fix_boy@fix_AnyStuff1 }
{917}{}{PID_SHIV@Вырежьте из дерева рукоять, а потом забейте в неё железяку. Получилось шило, универсальный инструмент для проделывания дырок.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 30@PID_METAL_TRASH 1&PID_FIREWOOD 1@PID_KNIFE 1@PID_SHIV 1@exp 50 script fix_boy@fix_AnyStuff1 }
{918}{}{PID_THROWING_KNIFE@Сбалансируйте и дополнительно заточите эту железку.@SK_THROWING 40@SK_THROWING 50&SK_REPAIR 30@PID_KNIFE 1@PID_MULTI_TOOL 1&PID_BOOK_OF_THROWING 1@PID_THROWING_KNIFE 1@exp 30 script fix_boy@fix_AnyStuff1 }
{919}{}{PID_SHOVEL@Приладьте лопату к черенку и прибейте гвоздями.@@SK_OUTDOORSMAN 40@PID_METAL_TRASH 1&PID_SHARPENED_POLE 1@@PID_SHOVEL 1@exp 40 script fix_boy@fix_AnyStuff1 }
{920}{}{PID_AXE@Найдите какую-нибудь ветку, насадите на неё железяку поострее.@@SK_OUTDOORSMAN 30@PID_FIREWOOD 1&PID_METAL_TRASH 1@@PID_AXE 1@exp 40 script fix_boy@fix_AnyStuff1 }
{921}{}{PID_SANDBAG_EMPTY@Сшейте мешок из кусков ткани.@@SK_OUTDOORSMAN 20@PID_RAGS 4&PID_POCKET_LINT 1@PID_SHIV 1@PID_SANDBAG_EMPTY 1@exp 30 script fix_boy@fix_Bag }
{922}{}{PID_SANDBAG_1@Если наполнить этот мешок песком, получится... мешок с песком!@@@PID_SANDBAG_EMPTY 1@PID_SHOVEL 1@PID_SANDBAG_1 1@exp 10 script fix_boy@fix_AnyStuff1 }
{923}{}{PID_SANDBAG_EMPTY@Если вдруг понадобился пустой мешок, то можно просто взять заполненный и освободить его от содержимого.@@@PID_SANDBAG_1 1@@PID_SANDBAG_EMPTY 1@ script fix_boy@fix_AnyStuff1 }
{924}{}{PID_POWER_FIST@Сшейте из шкур гекконов прочную перчатку, приспособьте механизм удара шипами при контакте с целью, питающийся от ядерных батареек. Противник надолго запомнит удар, нанесенный вами.@SK_UNARMED 50&SK_REPAIR 100@SK_UNARMED 70&SK_REPAIR 140&SK_SCIENCE 80@PID_GOLDEN_GECKO_PELT 3&PID_METAL_TRASH 6&PID_WELDING 1&PID_ELECTRONIC_WASTE 2&PID_V15_COMPUTER_PART 2&PID_SMALL_ENERGY_CELL 20@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1&PID_DEANS_ELECTRONICS 1&PID_SEWING_KIT 1&PID_BOOK_OF_MELEE_WEAPON 1@PID_POWER_FIST 1@exp 600 script fix_boy@fix_PowerFist }
{925}{}{PID_MEGA_POWER_FIST@Доработайте конструкцию силового кастета, вмонтировав в него систему электрических сверхпроводников с миниатюрным сверхъемким конденсатором, через которые цель будет поражать сильнейший электрический импульс. А металлические шипы замените на метало-керамические, способные пробить любую броню. Не забудьте про изоляцию!@SK_UNARMED 70&SK_REPAIR 100&SK_SCIENCE 100@SK_UNARMED 115&SK_REPAIR 175&SK_SCIENCE 200@PID_POWER_FIST 1&PID_TOUCH_SENSOR 1&PID_METAL_CERAMICS 2&PID_POLYMER 3&PID_SMALL_ENERGY_CELL 40&PID_MICRO_FUSION_CELL 75@PID_PROD_PLANT1_INV 1&PID_SUPER_TOOL_KIT 1&PID_DEANS_ELECTRONICS 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_BOOK_OF_MELEE_WEAPON 1@PID_MEGA_POWER_FIST 1@exp 2750 script fix_boy@fix_MegaPowerFist }

#Крафт ингредиенты

{950}{}{PID_POLYMER@Из обычного мусора разных сортов можно получить качественный полимерный материал, доверив контроль над протеканием химических процессов специализированной довоенной установке.@SK_SCIENCE 125@SK_SCIENCE 175@PID_PUMP_PARTS 4&PID_ELECTRONIC_WASTE 2&PID_CHEMICALS 2@PID_MULTICRAFT_INV 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_CHEMISTRY_MANUAL 1@PID_POLYMER 1@exp 500 script fix_boy@fix_Polymer }
{951}{}{PID_CARBON@Получите углеродное волокно путем нагрева текстильных волокон до очень высокой температуры. Покрыв их смолой, введите в скрученном виде в полимерную матрицу и получите материал, который в четыре раза прочнее стали того же веса.@SK_SCIENCE 145@SK_SCIENCE 195@PID_POLYMER 2&PID_FIREWOOD 7&PID_CHEMICALS 3&PID_RAGS 15@PID_MULTICRAFT_INV 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_CHEMISTRY_MANUAL 1@PID_CARBON 1@exp 666 script fix_boy@fix_Carbon }
{952}{}{PID_METAL_CERAMICS@Получите металлический порошок путем распыления расплавленного металла в среде инертных газов. Спекание металлического порошка с матрицей из нитрида кремния потребует огромного количества энергии, но получившийся композиционный материал не будет иметь равных по прочности в пустоши.@SK_SCIENCE 155@SK_SCIENCE 225@PID_FLINT 7&PID_METAL_ORE 4&PID_MINERAL 6&PID_CHEMICALS 6&PID_SMALL_ENERGY_CELL 80@PID_MULTICRAFT_INV 1&PID_BIG_BOOK_OF_SCIENCE 1&PID_CHEMISTRY_MANUAL 1@PID_METAL_CERAMICS 1@exp 999 script fix_boy@fix_MetalCeramics }
{953}{}{PID_LUBRICANT@Растопите браминий жир на огне, смешайте с некоторыми химикатами и получите простейшую смазку для оружия.@SK_OUTDOORSMAN 40@SK_OUTDOORSMAN 80@PID_MEAT 2&PID_CHEMICALS 1&PID_BOTTLE_EMPTY 1@PID_LIGHTER 1@PID_LUBRICANT 1@exp 88 script fix_boy@fix_AnyStuff1 }
{954}{}{PID_OPTIKAL_SIGHT@Настройте оптоэлектронный сенсор соответствующим образом, приделайте к нему крепления и получите высококлассный оптический прицел.@SK_REPAIR 90@SK_REPAIR 140&SK_SCIENCE 100@PID_OPTOELECTRONIC_SENSOR 1&PID_PUMP_PARTS 2@PID_SUPER_TOOL_KIT 1@PID_OPTIKAL_SIGHT 1@exp 210 script fix_boy@fix_AnyStuff1 }
{955}{}{PID_JUICE@Выжмите соки из браминьего кишечника при помощи веревки и деревянных распорок, залейте его в бутыль и получите ценнейший продукт. Обескровленный кишечник не выбрасывайте!@@SK_OUTDOORSMAN 60@PID_BOTTLE_EMPTY 1&PID_INTESTINES 1@PID_FIREWOOD 1&PID_ROPE 1@PID_JUICE 1&PID_INTESTINES_DRY 1@exp 50 script fix_boy@fix_AnyStuff1 }
{956}{}{PID_TOUCH_SENSOR@Спаяйте систему проводов по очертанию кисти руки, пригодную для вмонтирования в перчатку. Крошечный, но невероятно емкий конденсатор будет подавать на них ток в десяток ампер.@SK_REPAIR 120&SK_SCIENCE 120@SK_REPAIR 155&SK_SCIENCE 180@PID_METAL_TRASH 6&PID_ELECTRONIC_WASTE 8&PID_V15_COMPUTER_PART 6&PID_SUPER_CAPACITOR 1@PID_SUPER_TOOL_KIT 1&PID_DEANS_ELECTRONICS 1&PID_BIG_BOOK_OF_SCIENCE 1@PID_TOUCH_SENSOR 1@exp 1050 script fix_boy@fix_TouchSensor }
{957}{}{PID_REFINED_ORE@Благодаря секретной технологии хабологов, для обогащения урана больше не требуется целый завод.@SK_SCIENCE 155@SK_SCIENCE 190@PID_URANIUM_ORE 3&PID_SMALL_ENERGY_CELL 20@PID_MULTICRAFT_INV 1&PID_BIG_BOOK_OF_SCIENCE 1@PID_REFINED_ORE 1@exp 100 script fix_boy@fix_Uran }





#Уникальные предметы
{1000}{}{PID_ELEPHANT_GUN@Найдите токарный станок, используя его как сверлильный, рассверлите трубу до диаметра 17.8 мм, из куска металлического кола выточите затвор. По схемам из "Пушек и Пуль" изготовьте спусковой механизм, а приклад просто выточите из дерева.@SK_SCIENCE 90&SK_REPAIR 100@SK_SMALL_GUNS 190&SK_SCIENCE 120&SK_REPAIR 175@PID_TUBE 1&PID_PLANK 1&PID_FIREWOOD 1&PID_METAL_TRASH 6&PID_PUMP_PARTS 5&PID_STEEL 4&PID_WELDING 2&PID_700_NITRO_EXPRESS 2@PID_MANUFACT_LATHE_INV 1&PID_SUPER_TOOL_KIT 1&PID_OIL_CAN_TRUE 1&PID_GUNS_AND_BULLETS 1@PID_ELEPHANT_GUN 1@exp 2600 script fix_boy@fix_NitroExpress}
{1001}{}{PID_MULTI_BARREL_GUN@Несколько труб небольшого диаметра, распиленных на 19 одинаковых отрезков, и подведённые к каждому из них электрозапалы по схеме из "Пушек и пуль". Для производства необходим верстак.@SK_SCIENCE 70&SK_REPAIR 80@SK_SMALL_GUNS 140&SK_SCIENCE 120&SK_REPAIR 140@PID_TUBE 6&PID_FIREWOOD 2&PID_METAL_TRASH 5&PID_PUMP_PARTS 4&PID_SMALL_ENERGY_CELL 40&PID_V15_COMPUTER_PART 7&PID_ELECTRONIC_WASTE 6&PID_WELDING 1@PID_WORKBENCH_INV 1&PID_GUNS_AND_BULLETS 1&PID_DEANS_ELECTRONICS 1&PID_MULTI_TOOL 1@PID_MULTI_BARREL_GUN 1@exp 800 script fix_boy@fix_MultiBarrelGun }
{1002}{}{PID_METAL_STORM@Используйте 7 стволов от G11 для того, чтобы собрать самодельный пулемёт по схеме "Metalstorm", с продольным заряжанием безгильзовой аммуниции в ствол и активации её при помощи электрического запала. Придётся немного попаять.@SK_SCIENCE 160&SK_REPAIR 170@SK_BIG_GUNS 190&SK_SCIENCE 170&SK_REPAIR 210@PID_HK_G11 7&PID_METAL_TRASH 12&PID_PUMP_PARTS 14&PID_STEEL 6&PID_POLYMER 6&PID_METAL_CERAMICS 2&PID_ELECTRONIC_WASTE 18&PID_MICRO_FUSION_CELL 50&PID_V15_COMPUTER_PART 15&PID_WELDING 5&PID_4_7MM_CASELESS 140@PID_PROD_PLANT2_INV 1&PID_SUPER_TOOL_KIT 1&PID_OIL_CAN_TRUE 1&PID_BOOK_OF_HEAVY_WEAPON 1&PID_DEANS_ELECTRONICS 1@PID_METAL_STORM 1@exp 3600 script fix_boy@fix_VindicatorMinigun }
{1010}{}{PID_CHITIN_ARMOR@Разломать панцирь на мелкие куски. Осторожно помешивая, опустить в кипящие химикаты. На медленном огне варить смесь до растворения хитина и получения однородной массы. Расплав слоями перенести на ткань, каждый слой ткани и расплава отформовать по фигуре.@@SK_REPAIR 150&SK_OUTDOORSMAN 175&SK_SCIENCE 100&ST_INTELLECT 6@PID_RADSCORPION_PARTS 8&PID_CHEMICALS 4&PID_RAGS 12&PID_METAL_TRASH 9&PID_LEATHER_ARMOR 1&PID_BOTTLE_FULL 3@PID_FIREPIT_INV 1&PID_SUPER_TOOL_KIT 1&PID_CHEMISTRY_MANUAL 1@PID_CHITIN_ARMOR 1@exp 1400 script fix_boy@fix_ChitinArmor}

#Всякая хуйня

{1050}{}{PID_BAG@Из шкуры теленка получится отличная сумка для переноски вашего хлама.@@SK_OUTDOORSMAN 50&SK_REPAIR 40@PID_BRAHMIN_SKIN 1&PID_POCKET_LINT 1&PID_ROPE 1@PID_SEWING_KIT 1&PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_COMBAT_KNIFE 1@PID_BAG 1@exp 120 script fix_boy@fix_AnyStuff2 }
{1051}{}{PID_BACKPACK@Из двух шкур брамина сшейте вместительный мешок, а из шкур золотого геккона - лямки. В такой рюкзак поместится значительная часть ваших пожитков.@SK_OUTDOORSMAN 50@SK_OUTDOORSMAN 75&SK_REPAIR 70@PID_BRAHMIN_SKIN 2&PID_GOLDEN_GECKO_PELT 2&PID_POCKET_LINT 4&PID_ROPE 1@PID_SEWING_KIT 1&PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_COMBAT_KNIFE 1@PID_BACKPACK 1@exp 120 script fix_boy@fix_AnyStuff3 }
{1052}{}{PID_SEWING_KIT@Из шкуры гекко изготовьте удобный футляр, в который сложите все необходимое для шитья одежды.@@SK_OUTDOORSMAN 35@PID_GECKO_PELT 1&PID_POCKET_LINT 2&PID_METAL_TRASH 2@@PID_SEWING_KIT 1@exp 150 script fix_boy@fix_AnyStuff1 }
{1053}{}{PID_EXP_COLLAR_CRAFT@Из различного мусора соберите прочный ошейник, туго застегивающийся вокруг шеи. В ящичке верстака можно найти минипередатчик и детонатор, которые нужно подсоединить к куску пластиковой взрывчатки, встроенной в ошейник.@@@PID_PUMP_PARTS 1&PID_METAL_TRASH 1&PID_PLASTIC_EXPLOSIVES_DULL 1@PID_WORKBENCH_INV 1&PID_MULTI_TOOL 1@PID_EXP_COLLAR_CRAFT 1@exp 40 script fix_boy@fix_ExpCollar }
{1054}{}{PID_TRAP_PLANT_SPIKE@Найдите в мусоре несколько пружин помощнее и соберите простенький механизм для выстреливания шипов в семи направлениях. Наступит на неё геккон, или человек, им будет неприятно получить дополнительную дырку в заднице.@SK_OUTDOORSMAN 35@SK_OUTDOORSMAN 50&SK_REPAIR 100@PID_FIREWOOD 1&PID_PUMP_PARTS 3&PID_METAL_TRASH 2@PID_MULTI_TOOL 1@PID_TRAP_PLANT_SPIKE 1@exp 150 script fix_boy@fix_AnyStuff1 }



